kumahq/kuma-website

docs/docs/0.1.0/installation/debian.md, docs/docs/0.1.0/installation/ubuntu.md, docs/docs/0.1.1/installation/debian.md, docs/docs/0.1.2/installation/debian.md, docs/docs/0.1.2/installation/ubuntu.md
=> fix: broken links

docs/docs/0.1.2/documentation/README.md
KUMA_DATAPLANE_NAME=redis-1 ==> KUMA_DATAPLANE_NAME=backend-1
=> Updating Dataplane Entity

docs/docs/0.2.2/policies/README.md
=> docs(policies) mtls tip traffic permissions

docs/docs/0.2.0/documentation/README.md
Add documentation for kumactl delete functionality
=> docs: add kumactl delete

docs/docs/0.1.0/installation/ubuntu.md, docs/docs/0.1.1/installation/ubuntu.md, docs/docs/0.1.2/installation/ubuntu.md, docs/docs/0.2.0/installation/ubuntu.md, docs/docs/0.2.1/installation/ubuntu.md, docs/docs/0.2.2/installation/ubuntu.md, docs/docs/draft/installation/ubuntu.md
=> docs: fix formatting on Ubuntu installation pages

docs/docs/draft/documentation/README.md, docs/docs/draft/policies/README.md
* document `TrafficRoute`  REST API
=> docs: document TrafficRoute REST API

docs/docs/draft/documentation/README.md
=> docs(readme) cli generate

docs/README.md
=> docs(readme) dataplane token and changed cp address

docs/README.md
* part of docs outside of DRAFT
=> docs: update examples of Mesh resource on k8s to remove Namespace

docs/docs/0.3.0/policies/README.md, docs/docs/0.3.1/policies/README.md, docs/docs/draft/policies/README.md
0.3.1 missing the body paragraph for traffic route
=> docs: fix 0.3.1 traffic route docs

docs/docs/0.3.1/documentation/README.md, docs/docs/draft/documentation/README.md
I'll update also 0.3.1 directory once it's approved.
=> docs(readme) up to date env vars for exposing admin server

docs/docs/0.3.1/documentation/README.md, docs/docs/draft/documentation/README.md
I'll copy it to 0.3.1 once the PR is approved.
=> docs(readme) secure the connection between postgres and kuma-cp

docs/docs/0.3.1/policies/README.md, docs/docs/draft/policies/README.md
* Add `General notes about Kuma policies` section
* Add `How Kuma chooses the right policy to apply` section
=> docs: document how Kuma chooses the right policy to apply

docs/.vuepress/theme/components/custom/Home.vue, docs/.vuepress/theme/styles/custom/components/_newsbar.scss, docs/README.md
- News banner on homepage
- Static to keep things simple; no need to complicate by tying into dynamic source
- New content to reflect the new release
=> News banner

docs/docs/0.3.2/README.md
Some updates were lost in the 0.3.2 release, so this PR brings the overview section up to date again.
=> docs(overview) bringing overview up to date

bin/setup-redirects/index.js
Added additional Netlify redirect handling for form success URLs that contain queries.
- https://community.netlify.com/t/preserve-query-parameters-on-redirect/2226/21
- https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
=> Additional Netlify redirects

docs/policies.md
Change the "Traffic Trace" title to "Traffic Tracing".
=> Policies page text fix

CONTRIBUTING.md
=> docs(contributing) new contribution process

docs/docs/0.3.2/installation/centos.md, docs/docs/0.3.2/installation/debian.md, docs/docs/0.3.2/installation/kubernetes.md, docs/docs/0.3.2/installation/macos.md, docs/docs/0.3.2/installation/redhat.md, docs/docs/0.3.2/installation/ubuntu.md
Update the docs to show correct output for `kumactl get [..]` and downloading binary
=> docs: update kumactl output

docs/.vuepress/theme/store/index.js
Updated the form handler to use the new one supplied by the marketing team.
=> update the Community Call form handler

docs/docs/0.1.0/documentation/overview.md, docs/docs/0.1.1/documentation/overview.md, docs/docs/0.1.2/documentation/overview.md, docs/docs/0.2.0/documentation/overview.md, docs/docs/0.2.1/documentation/overview.md, docs/docs/0.2.2/documentation/overview.md, docs/docs/0.3.0/documentation/overview.md, docs/docs/0.3.1/documentation/overview.md, docs/docs/0.3.2/documentation/overview.md, docs/docs/0.4.0/documentation/overview.md
These are changes that were derived from [this PR](https://github.com/Kong/kuma-website/pull/130/files#diff-52e9a2fbf4cf6fe920061fc331b88d6e). I've only made the changes to the Documentation Overview page for v0.3.2. If these changes are good, I can make them across all of the other versions as well.
=> Kubernetes prerequisites content additions and revisions

docs/docs/0.4.0/documentation/backends.md
Info about Postgres DB migrations
=> docs(backends) db migrations

docs/docs/0.1.0/documentation/overview.md, docs/docs/0.1.1/documentation/overview.md, docs/docs/0.1.2/documentation/overview.md, docs/docs/0.2.0/documentation/overview.md, docs/docs/0.2.1/documentation/overview.md, docs/docs/0.2.2/documentation/overview.md, docs/docs/0.3.0/documentation/overview.md, docs/docs/0.3.1/documentation/overview.md, docs/docs/0.3.2/documentation/overview.md, docs/docs/0.4.0/documentation/overview.md
Hello, This PR will fix broken links to k8s yaml file of overview.
=> docs(overview): fix some broken links

docs/docs/0.4.0/documentation/fine-tuning.md
Added notes of tuning the performance of CP by scarifying the latency.
=> docs(documentation) fine tuning of snapshot generation

docs/docs/0.5.0/policies/mutual-tls.md, docs/docs/0.5.0/policies/traffic-trace.md
Updating the tracing documentation.
=> docs: updating traffic trace

docs/docs/0.5.1/documentation/dps-and-data-model.md
=> docs: replaces #215

docs/docs/0.6.0/documentation/deployments.md
The docs showed grpc connections where in real live they need to be grpcs
=> GRPC to GRPCS

docs/docs/0.6.0/documentation/dps-and-data-model.md, docs/docs/0.6.0/policies/traffic-log.md, docs/docs/0.6.0/policies/traffic-metrics.md, docs/docs/0.6.0/policies/traffic-route.md, docs/docs/0.6.0/quickstart/kubernetes.md, docs/docs/0.6.0/quickstart/universal.md
=> docs(*) fix service naming

docs/docs/0.6.0/documentation/dps-and-data-model.md
=> docs(*) add serviceAddress

docs/docs/0.6.0/documentation/deployments.md
=> docs(*) update Global/Remote deploy procedure

docs/docs/0.6.0/documentation/networking.md
=> docs(dns) clarification when to use `.mesh`

docs/docs/0.7.0/documentation/deployments.md
=> docs(*) clarify KDS and Ingress address usage for Distributed Deployments

docs/docs/0.7.0/overview/kuma-vs-xyz.md
Signed-off-by: Yuiko Mori <yuiko-mori@nec.com>
=> Fix typo in overview/kuma-vs-xyz.md

docs/docs/0.7.1/documentation/networking.md
Updating the outdated service discovery docs to describe new multi-zone discovery.
=> docs(*): updating service discovery docs

docs/docs/0.7.1/documentation/dps-and-data-model.md
=> docs(*) use tags for the outbound

docs/docs/0.7.1/policies/traffic-metrics.md
Fix for https://github.com/kumahq/kuma/issues/1005
=> DP override example corrected.

docs/docs/0.7.1/documentation/dps-and-data-model.md
update docs related to https://github.com/kumahq/kuma/pull/965
=> doc(kuma-cp) domain name as a 'dataplane.networking.address'

docs/docs/0.7.1/documentation/networking.md
=> docs(documentation) transparent proxying section

docs/_blog/2020-10-07-announce-maintainer-austince.md
Let me know how this looks, happy to change anything!
Signed-off-by: austin ce <austin.cawley@gmail.com>
/cc @nickolaev
=> feat(blog): add austince maintainer announcement

docs/docs/0.7.2/documentation/http-api.md
=> docs(*) fix API inconsistencies

docs/docs/0.7.0/quickstart/universal.md, docs/docs/0.7.1/quickstart/universal.md, docs/docs/0.7.2/quickstart/universal.md
Signed-off-by: YuikoTakada <y-mori@ti.jp.nec.com>
Fix #295
=> Fix Traffic Metric Policy in universal mode doc

docs/docs/0.7.2/documentation/networking.md
Bootstrap, XDS, SDS is served on one port.
Some ports were missing from the list
=> Adjust ports

docs/docs/0.7.3/README.md, docs/docs/0.7.3/documentation/backends.md, docs/docs/0.7.3/documentation/cli.md, docs/docs/0.7.3/documentation/dependencies.md, docs/docs/0.7.3/documentation/deployments.md, docs/docs/0.7.3/documentation/dps-and-data-model.md, docs/docs/0.7.3/documentation/networking.md, docs/docs/0.7.3/documentation/overview.md, docs/docs/0.7.3/documentation/secrets.md, docs/docs/0.7.3/installation/amazonlinux.md, docs/docs/0.7.3/installation/centos.md, docs/docs/0.7.3/installation/debian.md, docs/docs/0.7.3/installation/docker.md, docs/docs/0.7.3/installation/helm.md, docs/docs/0.7.3/installation/kubernetes.md, docs/docs/0.7.3/installation/macos.md, docs/docs/0.7.3/installation/openshift.md, docs/docs/0.7.3/installation/redhat.md, docs/docs/0.7.3/installation/ubuntu.md, docs/docs/0.7.3/overview/vm-and-k8s-support.md, docs/docs/0.7.3/overview/what-is-kuma.md, docs/docs/0.7.3/policies/circuit-breaker.md, docs/docs/0.7.3/policies/health-check.md, docs/docs/0.7.3/policies/mesh.md, docs/docs/0.7.3/policies/mutual-tls.md, docs/docs/0.7.3/policies/traffic-permissions.md, docs/docs/0.7.3/policies/traffic-route.md, docs/docs/0.7.3/policies/traffic-trace.md, docs/docs/0.7.3/quickstart/kubernetes.md, docs/docs/0.7.3/quickstart/universal.md
=> docs: updating 0.7.3 links to point to 0.7.3

docs/docs/0.7.1/documentation/deployments.md
After https://github.com/kumahq/kuma/pull/1038
=> docs(*) merge install ingress into install control-plane

docs/docs/0.7.3/documentation/dps-and-data-model.md, docs/docs/0.7.3/policies/protocol-support-in-kuma.md
=> docs(*) support for kafka protocol

docs/docs/0.7.2/policies/mesh.md, docs/docs/0.7.3/policies/mesh.md
=> fix(*) passthrough on a Mesh update

docs/docs/0.7.3/policies/traffic-metrics.md
=> chore(policies) change mads port

docs/docs/0.7.3/policies/circuit-breaker.md, docs/docs/0.7.3/policies/fault-injection.md, docs/docs/0.7.3/policies/health-check.md, docs/docs/0.7.3/policies/mesh.md, docs/docs/0.7.3/policies/proxy-template.md, docs/docs/0.7.3/policies/traffic-log.md, docs/docs/0.7.3/policies/traffic-metrics.md, docs/docs/0.7.3/policies/traffic-permissions.md, docs/docs/0.7.3/policies/traffic-route.md
=> chore(policies) change scope of resources to global

docs/docs/0.7.3/documentation/http-api.md
=> doc(kuma-cp) API endpoint for Mesh Insights

docs/docs/0.7.3/policies/traffic-log.md
=> doc(kuma-cp) traffic direction

docs/docs/0.7.3/policies/mutual-tls.md, docs/docs/0.7.3/policies/traffic-permissions.md
=> feat(policies) traffic permission is created by default

docs/docs/1.0.0/policies/traffic-route.md
=> docs(policies) add default traffic route

docs/docs/1.0.1/documentation/networking.md
=> doc(*) proper place for 5685

docs/docs/1.0.1/documentation/networking.md
A revamp of the lost https://github.com/kumahq/kuma-website/pull/299
=> docs(*) update ports

docs/docs/1.0.1/documentation/http-api.md, docs/docs/1.0.1/policies/health-check.md
=> docs(kuma-cp) fix health checks

yarn.lock
Apparently, we need to do this form time to time.
=> chore(*) yarn upgrade

docs/docs/1.0.1/documentation/http-api.md
=> feat(http-api) service insights

docs/docs/1.0.1/documentation/deployments.md, docs/docs/1.0.1/documentation/http-api.md
=> docs(*) multizone updates

docs/docs/1.0.2/documentation/networking.md, docs/docs/1.0.2/policies/proxy-template.md
Aftermath of https://github.com/kumahq/kuma/pull/1139
=> docs(*) update envoy.filters.* usage in docs

docs/docs/1.0.3/documentation/http-api.md, docs/docs/1.0.3/policies/health-check.md
Reverts kumahq/kuma-website#338
=> Revert "FOR NEXT docs(*) http health checks"

docs/docs/1.0.3/policies/fault-injection.md
=> fix(*) ignore faultinjection source protocol

yarn.lock
=> chore(*) upgrades

docs/docs/1.0.3/policies/protocol-support-in-kuma.md
=> docs(*) tls support

docs/docs/1.0.3/documentation/http-api.md, docs/docs/1.0.3/policies/health-check.md
Re-opening https://github.com/kumahq/kuma-website/pull/338 against `next`.
=> docs(*) http health checks

docs/.vuepress/theme/styles/custom/base/_type-and-content.scss, docs/.vuepress/theme/styles/vuepress-core/code.scss, docs/.vuepress/theme/styles/vuepress-core/config.scss, docs/.vuepress/theme/styles/vuepress-core/mobile.scss
This was occurring because there were a few VuePress core theme (and custom theme) styles that were not carrying over into the blog page styles.
=> Code block overflow fix

docs/.vuepress/theme/styles/custom/components/_newsbar.scss, docs/.vuepress/theme/styles/custom/pages/_page-home.scss
These are carried over from [feat/email-capture-changes](https://github.com/kumahq/kuma-website/tree/feat/email-capture-changes) for deployment to the homepage.
=> Homepage masthead and news bar revisions

docs/docs/1.0.6/documentation/deployments.md, docs/docs/1.0.6/documentation/networking.md
=> docs(*) alternative RFC compliant DNS names

docs/docs/1.0.8/documentation/http-api.md
Blocked be this PR: https://github.com/kumahq/kuma/pull/1563
=> feat(*) insights API update

docs/.vuepress/enhanceApp.js
Signed-off-by: Daryn St. Pierre <daryn.st.pierre@konghq.com>
=> removed a duplicate call to kongponents styles

docs/README.md, yarn.lock
Remove Telus testimonial.
Not sure about `yarn.lock` -- upgraded locally, didn't expect changes in repo. lmk if I should revert.
PTAL @bloqhead
=> remove telus testimonial for now

docs/docs/1.0.8/networking/transparent-proxying.md
=> fix(networking) correct user name in transparent proxy

docs/.vuepress/site-config/sidebar-nav.js, docs/docs/1.0.8/networking/cni.md
=> docs(*) cni

docs/docs/1.1.1/policies/circuit-breaker.md
Docs for https://github.com/kumahq/kuma/pull/1688
**Caution!** current PR against `master`, don't merge unless https://github.com/kumahq/kuma/pull/1688 is backported to `release-1.1` branch
=> doc(kuma-cp) circuit breaker thresholds

docs/docs/1.1.1/networking/transparent-proxying.md
=> docs(tp) add firewalld support

docs/docs/1.1.1/policies/traffic-trace.md
=> docs(*) highlight the protocol support in traffic tracing

docs/.vuepress/site-config/sidebar-nav.js, docs/docs/1.1.2/networking/ipv6.md
=> docs(*) ipv6 support

docs/docs/1.1.2/networking/dns.md, docs/docs/1.1.2/policies/external-services.md
=> docs(*) builtin DNS

docs/docs/1.1.4/networking/transparent-proxying.md
=> docs(*) transparen proxy upgrade clarifications

docs/.vuepress/public/installer.sh, docs/docs/1.1.4/installation/amazonlinux.md, docs/docs/1.1.4/installation/centos.md, docs/docs/1.1.4/installation/debian.md, docs/docs/1.1.4/installation/docker.md, docs/docs/1.1.4/installation/eks.md, docs/docs/1.1.4/installation/kubernetes.md, docs/docs/1.1.4/installation/macos.md, docs/docs/1.1.4/installation/openshift.md, docs/docs/1.1.4/installation/redhat.md, docs/docs/1.1.4/installation/ubuntu.md
=> docs(*) migrate from bintray

docs/docs/1.1.5/policies/proxy-template.md
=> docs(*) migrate ProxyTemplate to XDS v3

docs/docs/1.1.5/networking/dns.md
Updating to hopefully clear up a bit of confusion between K8s and Universal mode configurations of DNS/transparent-proxy.
=> docs(*) adding clarity for to dns docs for k8s vs universal

docs/docs/1.1.6/policies/traffic-permissions.md
=> docs(policies) traffic permission accepts all the tags

docs/.vuepress/public/installer.sh
=> chore(*) installer.sh support HTTP1/HTTP2 downloads

OWNERS.md
=> docs(*) update OWNERS

docs/docs/1.0.0/documentation/deployments.md, docs/docs/1.0.1/documentation/deployments.md, docs/docs/1.0.2/documentation/deployments.md, docs/docs/1.0.3/documentation/deployments.md, docs/docs/1.0.4/documentation/deployments.md, docs/docs/1.0.5/documentation/deployments.md, docs/docs/1.0.6/documentation/deployments.md, docs/docs/1.0.7/deployments/multi-zone.md, docs/docs/1.0.8/deployments/multi-zone.md, docs/docs/1.1.0/deployments/multi-zone.md, docs/docs/1.1.1/deployments/multi-zone.md, docs/docs/1.1.2/deployments/multi-zone.md, docs/docs/1.1.3/deployments/multi-zone.md, docs/docs/1.1.4/deployments/multi-zone.md, docs/docs/1.1.5/deployments/multi-zone.md, docs/docs/1.1.6/deployments/multi-zone.md
Signed-off-by: James Peach <james.peach@konghq.com>
=> docs(*) fix typo of 'identifies as'

docs/docs/1.0.7/documentation/dps-and-data-model.md, docs/docs/1.0.8/documentation/dps-and-data-model.md, docs/docs/1.1.0/documentation/dps-and-data-model.md, docs/docs/1.1.1/documentation/dps-and-data-model.md, docs/docs/1.1.2/documentation/dps-and-data-model.md, docs/docs/1.1.3/documentation/dps-and-data-model.md, docs/docs/1.1.4/documentation/dps-and-data-model.md, docs/docs/1.1.5/documentation/dps-and-data-model.md, docs/docs/1.1.6/documentation/dps-and-data-model.md
Signed-off-by: James Peach <james.peach@konghq.com>
=> docs(*) fix typo in "dataplane"

docs/docs/1.2.0/networking/dns.md
As the dataplane proxy build in DNS is enabled by default now
I reorganized the docs a little bit to reflect the change
=> chore(*) modify dns docs after change in defaults

docs/docs/1.2.0/policies/external-services.md
=> docs(policies) external service allow renegotiation

docs/docs/1.2.0/deployments/multi-zone.md
=> chore(deployments) remove install dns

docs/docs/1.2.0/deployments/multi-zone.md
Add missing flag for running ZoneIngress
=> fix(docs) add flag '--proxy-type=ingress'

docs/docs/1.2.0/deployments/multi-zone.md
@jpeach correct documentation of generating ingress token
=> correct generate ingress token command

docs/README.md
Signed-off-by: Jennifer Rondeau <jennifer.rondeau@konghq.com>
=> fix typo on home page

docs/docs/1.2.0/documentation/dps-and-data-model.md
=> fix new line command in kuma-dp run

docs/docs/1.2.1/deployments/multi-zone.md
=> fix(docs) add a warning for Zone CP in-memory

docs/docs/1.2.1/policies/traffic-trace.md
=> chore(policies) TrafficTrace also works with http2 and grpc

docs/docs/1.0.0/documentation/dps-and-data-model.md, docs/docs/1.0.1/documentation/dps-and-data-model.md, docs/docs/1.0.2/documentation/dps-and-data-model.md, docs/docs/1.0.3/documentation/dps-and-data-model.md, docs/docs/1.0.4/documentation/dps-and-data-model.md, docs/docs/1.0.5/documentation/dps-and-data-model.md, docs/docs/1.0.6/documentation/dps-and-data-model.md, docs/docs/1.0.7/documentation/health.md, docs/docs/1.0.8/documentation/health.md, docs/docs/1.1.0/documentation/health.md, docs/docs/1.1.1/documentation/health.md, docs/docs/1.1.2/documentation/health.md, docs/docs/1.1.3/documentation/health.md, docs/docs/1.1.4/documentation/health.md, docs/docs/1.1.5/documentation/health.md, docs/docs/1.1.6/documentation/health.md, docs/docs/1.2.0/documentation/health.md, docs/docs/1.2.1/documentation/health.md
Fix some minor spelling errors.
=> docs(*) fix some spelling errors

docs/docs/1.2.2/documentation/http-api.md
=> fix(http-api) /status/zones does not contain URL

docs/docs/1.2.3/installation/helm.md
The namespace is now created by the helm chart
=> Remove namespace creation in helm install doc

docs/docs/1.2.3/policies/traffic-log.md, docs/docs/1.2.3/policies/traffic-trace.md
The docs were not very clear (some trace config was explained in the log docs).
This cleans this a little.
=> Improve log and trace docs for grafana

docs/docs/1.2.3/policies/protocol-support-in-kuma.md
=> feat(*) add websockets to supported protocols

docs/docs/1.2.3/documentation/http-api.md
will be available in the next major
=> docs(http-api) new fields in dataplane and mesh insights

docs/docs/1.2.3/policies/external-services.md
This should go to `next`. Because of lagging `next` and `next-release` I'm creating this PR to master for now.
=> [wip] docs(policies) external service sni

docs/docs/1.2.3/documentation/http-api.md
I had to change some fields after initial implementation https://github.com/kumahq/kuma-website/pull/505
=> docs(http-api) adjust insight fields

docs/.vuepress/site-config/sidebar-nav.js, docs/docs/1.2.3/policies/virtual-outbound.md, docs/policies.md
=> Add documentation for virtual-outbound

docs/docs/1.3.0/documentation/http-api.md
- We had wrong urls to zones+insights
- Added config into zones+insights subscription (as it was added recently)
=> docs(http-api) adjust zones docs

docs/docs/1.3.0/policies/mutual-tls.md
Signed-off-by: Jennifer Rondeau <jennifer.rondeau@konghq.com>
Make distinction between CA and certificate it generates clearer, add example cert file
=> clarify instructions, add example

docs/docs/1.1.0/networking/cni.md, docs/docs/1.1.1/networking/cni.md, docs/docs/1.1.2/networking/cni.md, docs/docs/1.1.3/networking/cni.md, docs/docs/1.1.4/networking/cni.md, docs/docs/1.1.5/networking/cni.md, docs/docs/1.1.6/networking/cni.md, docs/docs/1.2.0/networking/cni.md, docs/docs/1.2.1/networking/cni.md, docs/docs/1.2.2/networking/cni.md, docs/docs/1.2.3/networking/cni.md, docs/docs/1.3.0/networking/cni.md
Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>
=> correct typo

docs/docs/1.2.0/policies/traffic-permissions.md, docs/docs/1.2.1/policies/traffic-permissions.md, docs/docs/1.3.0/policies/traffic-permissions.md
Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>
=> correct typos

docs/docs/1.2.3/networking/dns.md, docs/docs/1.3.0/networking/dns.md
CoreDNS wasn't mentionned anywhere, explain how DPP DNS works
and how to update the template
=> docs(dns) add extra documentation on the DNS

docs/docs/1.3.0/policies/virtual-outbound.md
=> Correct bad K8s spec in virtual-outbound

docs/docs/1.3.0/documentation/dps-and-data-model.md
Fix the spelling of "Kuma".
Signed-off-by: James Peach <james.peach@konghq.com>
=> Fix a spelling error.

docs/docs/1.3.0/policies/traffic-metrics.md
=> add prometheus relabel config

docs/.vuepress/site-config/sidebar-nav.js, docs/docs/1.3.0/other/compatibility.md
=> Add minimum k8s version to documentation

docs/docs/1.3.0/security/certificates.md
=> docs(security) service account token considerations

docs/docs/4.4.4/policies/fault-injection.md
=> docs(kuma-cp) add tabs for Fault Injection policy

docs/docs/4.4.4/documentation/http-api.md
=> docs(api) add Global Insights endpoint to api ref

docs/.vuepress/site-config/sidebar-nav.js, docs/docs/4.4.4/security/api-access-control.md
=> docs(security) access control

docs/docs/1.3.1/policies/traffic-metrics.md
=> Add datasource documentation

docs/docs/4.4.4/documentation/http-api.md
Structure of GlobalInsights changed to allow return more of global
resources
=> docs(api) add resources to GlobalInsights + more

docs/docs/4.4.4/documentation/dps-and-data-model.md, docs/docs/4.4.4/documentation/kubernetes-annotations.md, docs/docs/4.4.4/documentation/overview.md, docs/docs/4.4.4/quickstart/kubernetes.md
We are changing the way how we mark namespaces and pods.
https://github.com/kumahq/kuma/pull/3417
=> docs(dp) sidecar injection with label

docs/docs/1.4.1/documentation/cli.md, docs/docs/1.4.1/quickstart/kubernetes.md
We were linking to a part of the doc that moved
fix #418 
=> docs: fix bad link in kumactl docs

docs/.vuepress/site-config/sidebar-nav.js, docs/docs/1.4.1/community/data-collection.md
=> docs: data collection under reference docs section

docs/.vuepress/config.js
=> fix(config) remove quotes

docs/docs/1.2.x/policies/traffic-route.md, docs/docs/1.3.x/policies/traffic-route.md, docs/docs/1.4.x/policies/traffic-route.md, docs/docs/dev/policies/traffic-route.md
=> fix: bad yaml in traffic-route examples

docs/docs/1.4.x/documentation/cli.md, docs/docs/dev/documentation/cli.md
=> feat: document kumactl apply variables

docs/.vuepress/theme/components/custom/DistibutionDropdown.vue, docs/.vuepress/theme/components/custom/Home.vue, docs/README.md
It will add an  option to select distribution
=> feat(home) add distribution dropdown

docs/docs/dev/documentation/http-api.md
HTTP ref for:
https://github.com/kumahq/kuma/pull/3462 
https://github.com/kumahq/kuma/pull/3568
=> docs(kuma-cp) add HTTP ref for Inspect API

docs/docs/1.4.x/documentation/configuration.md, docs/docs/dev/documentation/configuration.md
=> fix: bad $ prefix in shell command examples in configuration

docs/docs/dev/security/dp-membership.md
=> fix(membership): update membership syntax

docs/docs/1.4.x/deployments/multi-zone.md, docs/docs/dev/deployments/multi-zone.md
=> fix(multi-zone): replace remote to zone in mode

docs/.vuepress/theme/components/custom/DistibutionDropdown.vue
=> chore(main-page): adjust dropdown

docs/docs/dev/policies/locality-aware.md
Add explanation of locality-awareness.
=> docs(policies): add explanation of locality-aware load balancing

docs/docs/dev/documentation/fine-tuning.md
Added reachable services to fine tuning. Here I describe it with a bit more technical details, because I feel like `Fine tuning` is advanced section in the docs.
=> docs(documentation) add reachable services to fine tuning

docs/.vuepress/config.js, docs/.vuepress/public/robots.txt
Before we had to update this file to skip crawling of old versions.
This auto generates it!
=> feat(robots.txt): auto generate the robots.txt

docs/docs/dev/documentation/http-api.md, docs/docs/dev/documentation/inspect-api.md, docs/docs/dev/policies/how-kuma-chooses-the-right-policy-to-apply.md, docs/docs/dev/sidebar.json
Docs for Inspect API
Fix: https://github.com/kumahq/kuma-website/issues/683
=> docs(*): add docs for inspect api

docs/docs/dev/documentation/health.md, docs/docs/dev/policies/service-health-probes.md, docs/docs/dev/sidebar.json
Add summary of health check methods available within Kuma.
=> docs(kuma-cp): Add summary of health check methods

.github/workflows/ci.yml
=> chore(ci): broken link checker reduce verbosity

docs/docs/dev/policies/how-kuma-chooses-the-right-policy-to-apply.md
https://github.com/kumahq/kuma-website/issues/622
Added examples from the ticket linked in the issue, since I thought that was pretty clear + explanatory text.
=> docs(kuma-cp): add policy matching clarification

docs/docs/1.4.x/policies/external-services.md, docs/docs/dev/policies/external-services.md
ExternalSerivice is not namespaced scope
=> chore(policies): remove namespace from ExternalService

docs/docs/dev/policies/mutual-tls.md
Remove file from data source usages since it's deprecated now
=> docs(policies): remove file examples from data source

docs/docs/1.5.x/installation/docker.md, docs/docs/dev/installation/docker.md
=> fix(docker): correct version in docker install

docs/docs/dev/policies/proxy-template.md
Add proxy template listener tags matcher
=> feat(policies): proxy template listener tags

.github/workflows/sync-generated.yml
=> fix(ci): don't create new branches for new sync-generated

docs/docs/dev/deployments/multi-zone.md, docs/docs/dev/documentation/zoneegress.md, docs/docs/dev/policies/mesh.md
Added docs for new `Mesh` property `routing.zoneEgress` that forces traffic to go through `ZoneEgress` introduced in https://github.com/kumahq/kuma/pull/4013
=> feat(docs): added new property in mesh description

docs/docs/dev/documentation/gateway-api.md
TLS termination for Gateway API
=> docs(documentation): TLS termination for Gateway API

docs/.vuepress/config.js, docs/docs/dev/generated/cmd/kumactl/kumactl_inspect.md, docs/docs/dev/generated/cmd/kumactl/kumactl_inspect_meshgateway.md, docs/docs/dev/generated/kuma-cp.md, sync_generated.sh
This has been asked multiple times. It shows all possible
defaults and matching environment variables for the CP.
=> feat(generated): add generated kuma-cp.yaml example

docs/docs/dev/documentation/http-api.md
=> docs(inspect): add meshgateways/*/dataplanes to API reference

docs/docs/dev/documentation/http-api.md
=> docs(inspect): add MeshGateway Dataplane example for dataplanes/*/policies

docs/docs/dev/policies/external-services.md
Changed a bit docs about `ExternalServices`.
* added information about protocols
* added informations about tags that are taken into account while generating configuration
#751
=> feat(docs): updated docs of external services

docs/docs/1.5.x/documentation/http-api.md, docs/docs/dev/documentation/http-api.md
Added missing options and fixed paths
Signed-off-by: Łukasz Dziedziak <lukidzi@gmail.com>
=> feat(docs): updated docs for http api

docs/docs/dev/documentation/http-api.md
=> docs(inspect): add MeshGatewayDataplane to policy/*/dataplanes example

docs/docs/dev/documentation/configuration.md
=> fix(config): link to the kuma-cp reference config

docs/docs/dev/documentation/health.md, docs/docs/dev/policies/service-health-probes.md
It wasn't always clear especially in the case of Kubernetes
Fix #705
=> chore(health): rewrite health probe doc

docs/docs/dev/explore/dpp-on-kubernetes.md, docs/docs/dev/explore/dpp-on-universal.md
Fix https://github.com/kumahq/kuma-website/issues/606
=> docs(*): DPP lifecycle for universal and k8s

docs/docs/1.6.x/documentation/requirements.md, docs/docs/1.6.x/sidebar.json, docs/docs/dev/documentation/requirements.md, docs/docs/dev/sidebar.json
=> feat(requirements): add info on what's needed to run Kuma

.github/workflows/ci.yml, docs/.vuepress/config.js
=> fix(install): add a perm redirect for installing gateway

docs/_snippets/install_kumactl.md, docs/_snippets/install_os.md, docs/docs/1.6.x/policies/traffic-log.md, docs/docs/dev/policies/traffic-log.md
=> fix(logs): refresh traffic-log page

docs/docs/dev/reference/kubernetes-annotations.md
Add documentation of experimental transparent proxy engine annotation.
=> docs(kuma-cp): experimental transparent proxy engine annotation

docs/docs/1.1.x/policies/retry.md, docs/docs/1.2.x/policies/retry.md, docs/docs/1.3.x/policies/retry.md, docs/docs/1.4.x/policies/retry.md, docs/docs/1.5.x/policies/retry.md, docs/docs/1.6.x/policies/retry.md, docs/docs/dev/policies/retry.md
=> docs(retry): fix typo on retry policy

docs/docs/1.4.x/documentation/kubernetes-annotations.md, docs/docs/1.5.x/documentation/kubernetes-annotations.md, docs/docs/1.6.x/reference/kubernetes-annotations.md, docs/docs/dev/reference/kubernetes-annotations.md
=> doc: fix formatting for `kuma.io/ignore` example

docs/docs/dev/explore/gateway-api.md, docs/docs/dev/explore/gateway.md
=> docs(*): remove mentioning of '--experimental-meshgateway' flag

docs/docs/dev/documentation/requirements.md
=> docs(*): update envoy version in requirements

docs/docs/1.6.x/reference/kubernetes-annotations.md, docs/docs/dev/reference/kubernetes-annotations.md
=> fix: add `reachable-services` to k8s annotations reference

docs/.vuepress/public/installer.sh, docs/docs/dev/documentation/requirements.md, docs/docs/dev/other/compatibility.md
Added information about supported architecture and edited installer to detect arch type.
Fix #816
=> docs(*): added info about arm and installer detect arch

docs/.vuepress/theme/styles/vuepress-core/sidebar.scss
=> fix: proper scrolling on sidebar menu

docs/docs/dev/explore/dpp-on-kubernetes.md, docs/docs/dev/reference/kubernetes-annotations.md
Add custom container configuration docs
=> docs: custom container configuration

docs/docs/1.6.x/explore/gateway-api.md, docs/docs/dev/explore/gateway-api.md
=> fix: deadlink in gateway api docs

docs/docs/1.1.x/policies/fault-injection.md, docs/docs/1.2.x/policies/fault-injection.md, docs/docs/1.3.x/policies/fault-injection.md, docs/docs/1.4.x/policies/fault-injection.md, docs/docs/1.5.x/policies/fault-injection.md, docs/docs/1.6.x/policies/fault-injection.md, docs/docs/dev/policies/fault-injection.md
=> fix(*): fault injection protocols

docs/docs/dev/explore/dpp-on-kubernetes.md
Signed-off-by: Shaun Becker <6895147+shaunofneuron@users.noreply.github.com>
Fixes formatting of nested numbered list (4 spaces instead of two), removed period for consistency and fluff.
=> docs: fixes nested list formatting in dpp-on-kubernetes

docs/docs/1.6.x/reference/kubernetes-annotations.md, docs/docs/dev/reference/kubernetes-annotations.md
Clarifying how the volume should look for manually mounting token/certs.
=> fix: clarify token volume annotation requirements

docs/docs/1.6.x/reference/kubernetes-annotations.md, docs/docs/dev/reference/kubernetes-annotations.md
=> fix: volume annotation

docs/_blog/2022-04-12-kuma-1-7-0.md
=> fix: add container patches in announcement blogpost

.github/workflows/ci.yml, docs/.vuepress/public/installer.sh
```
curl -L https://deploy-preview-865--kuma.netlify.app/installer.sh | bash -
```
It was exiting even if the DL would work.
I'll work on running these tests in CI.
=> fix(installer.sh): actually download kumactl if possible

.github/workflows/ci.yml
=> chore(.github): add note about GH check

docs/.vuepress/public/installer.sh
=> feat(installer.sh): allow overriding $DISTRO

docs/docs/dev/explore/dpp-on-universal.md, docs/docs/dev/explore/dpp.md, docs/docs/dev/networking/networking.md
=> docs(explore/dpp): rework dpp page

docs/docs/1.7.x/explore/observability.md, docs/docs/dev/explore/observability.md
=> docs(observability): remove TrafficMetrics references

docs/docs/1.6.x/policies/mesh-gateway.md, docs/docs/1.7.x/policies/mesh-gateway.md, docs/docs/dev/policies/mesh-gateway.md
=> fix(gateway): correct bad tls example

docs/docs/1.7.x/explore/gateway.md, docs/docs/dev/explore/gateway.md
Closes https://github.com/kumahq/kuma-website/issues/892
[rendered](https://deploy-preview-894--kuma.netlify.app/docs/1.7.x/explore/gateway/#builtin)
=> docs(gateway): add MeshGatewayInstance customization hint

docs/docs/1.5.x/documentation/gateway.md, docs/docs/1.6.x/explore/gateway.md, docs/docs/1.7.x/explore/gateway.md, docs/docs/dev/explore/gateway.md
Closes https://github.com/kumahq/kuma-website/issues/904
=> docs(gateway): make MeshGatewayRoute kuma-demo compatible

docs/docs/1.5.x/documentation/gateway.md, docs/docs/1.6.x/explore/gateway.md, docs/docs/1.7.x/explore/gateway.md, docs/docs/dev/explore/gateway.md
Closes https://github.com/kumahq/kuma-website/issues/905
=> docs(gateway): add Namespace to MeshGateway Instance

docs/docs/dev/policies/mesh-gateway-route.md
Closes https://github.com/kumahq/kuma-website/issues/906
=> docs(meshgatewayroute): add info about filters

.github/workflows/sync-generated.yml
Right now none of the GH actions run for these PRs.
=> fix(.github): use GitHub app to get token for pushing

.github/workflows/ci.yml
=> fix(.github): only run styles when relevant files changed

docs/docs/dev/quickstart/kubernetes.md
Closes https://github.com/kumahq/kuma-website/issues/916
=> docs(quickstart): add note about gateways in kuma-counter-demo

docs/.vuepress/public/googleed9eef1af8bc72a5.html
=> fix: add google search console verification

docs/docs/dev/policies/traffic-metrics.md
Added docs about filtering Envoy's metrics. 
fix: #921
=> docs(*): added docs for filtering Envoy's metrics

docs/.vuepress/config.js
=> fix(search): add back searchbar

docs/.vuepress/_snippets/install_kumactl.md
It was not working at all when specifying any non-latest version
Fixes: https://github.com/kumahq/kuma-website/issues/946
=> fix: move VERSION var in install_kumactl snippet

docs/docs/dev/explore/observability.md
Fixes: https://github.com/kumahq/kuma-website/issues/959
=> docs(explore/observability): add stdout logging example for Loki

docs/docs/dev/explore/gateway.md
Closes https://github.com/kumahq/kuma-website/issues/931
See note at https://deploy-preview-961--kuma.netlify.app/docs/dev/explore/gateway/#builtin
=> docs(gateway): add note about envoy best practice configuration

docs/docs/dev/networking/cni.md
Expand CNI page in docs, add:
- different configurations
- logs location
Closed https://github.com/kumahq/kuma-website/issues/957
=> docs(cni): Add more info to CNI docs

docs/docs/dev/networking/cni.md
simplify weird sentence in cni docs
=> fix(cni): simplify weird sentence in cni docs

docs/.vuepress/theme/styles/custom/base/_type-and-content.scss
Signed-off-by: Adithya Krishna <adikrish@redhat.com>
This PR Fixes #867 
**Screen recording:**
[Issue867.webm](https://user-images.githubusercontent.com/23498248/186358056-c1a65706-03fd-442c-896e-800c91bd149d.webm)
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits) - Yes
=> [Bug] - Fixed Copy Icon scrolling horizontally

docs/docs/1.3.x/documentation/configuration.md, docs/docs/1.4.x/security/api-server-auth.md, docs/docs/1.5.x/installation/docker.md, docs/docs/1.5.x/security/api-server-auth.md, docs/docs/1.6.x/installation/docker.md, docs/docs/1.6.x/security/api-server-auth.md, docs/docs/1.7.x/installation/docker.md, docs/docs/1.8.x/installation/docker.md, docs/docs/dev/installation/docker.md
Signed-off-by: SADIK KUZU <sadikkuzu@hotmail.com>
Remove second $ from shell command:
Yes
Yes
=> Remove duplicate $ from shell command

docs/docs/1.8.x/deployments/multi-zone.md, docs/docs/dev/deployments/multi-zone.md
=> docs(multi-zone) fix helm install commands in multizone deployment

docs/docs/1.7.x/explore/gateway-api.md, docs/docs/1.7.x/policies/circuit-breaker.md, docs/docs/1.7.x/policies/fault-injection.md, docs/docs/1.7.x/policies/health-check.md, docs/docs/1.7.x/policies/how-kuma-chooses-the-right-policy-to-apply.md, docs/docs/1.7.x/policies/rate-limit.md, docs/docs/1.7.x/policies/retry.md, docs/docs/1.7.x/policies/timeout.md, docs/docs/1.7.x/policies/traffic-permissions.md, docs/docs/1.7.x/policies/traffic-route.md, docs/docs/1.8.x/explore/gateway-api.md, docs/docs/1.8.x/policies/circuit-breaker.md, docs/docs/1.8.x/policies/fault-injection.md, docs/docs/1.8.x/policies/health-check.md, docs/docs/1.8.x/policies/how-kuma-chooses-the-right-policy-to-apply.md, docs/docs/1.8.x/policies/rate-limit.md, docs/docs/1.8.x/policies/retry.md, docs/docs/1.8.x/policies/timeout.md, docs/docs/1.8.x/policies/traffic-permissions.md, docs/docs/1.8.x/policies/traffic-route.md, docs/docs/dev/explore/gateway-api.md, docs/docs/dev/policies/circuit-breaker.md, docs/docs/dev/policies/fault-injection.md, docs/docs/dev/policies/health-check.md, docs/docs/dev/policies/how-kuma-chooses-the-right-policy-to-apply.md, docs/docs/dev/policies/rate-limit.md, docs/docs/dev/policies/retry.md, docs/docs/dev/policies/timeout.md, docs/docs/dev/policies/traffic-permissions.md, docs/docs/dev/policies/traffic-route.md
=> fix(policies): add whether policies are inbound or outbound

docs/docs/1.6.x/explore/zone-ingress.md, docs/docs/1.7.x/explore/zone-ingress.md, docs/docs/1.8.x/explore/zone-ingress.md, docs/docs/dev/explore/zone-ingress.md
=> fix: add default zone-ingress port

docs/.vuepress/_snippets/install_kumactl.md, docs/.vuepress/_snippets/install_os.md
=> fix: ln command was assuming current directory

docs/docs/1.7.x/explore/gateway-api.md, docs/docs/1.8.x/explore/gateway-api.md, docs/docs/dev/explore/gateway-api.md
=> fix: make it explicit that gateway-api only works in standalone

docs/docs/1.6.x/quickstart/kubernetes.md, docs/docs/1.7.x/quickstart/kubernetes.md, docs/docs/1.8.x/quickstart/kubernetes.md, docs/docs/dev/quickstart/kubernetes.md
=> fix: remove namespace for trafficpermission

docs/docs/1.8.x/explore/gateway.md, docs/docs/dev/explore/gateway.md
=> fix: remove experimental from the gateway

docs/docs/1.1.x/quickstart/kubernetes.md, docs/docs/1.1.x/quickstart/universal.md, docs/docs/1.2.x/quickstart/kubernetes.md, docs/docs/1.2.x/quickstart/universal.md, docs/docs/1.3.x/quickstart/kubernetes.md, docs/docs/1.3.x/quickstart/universal.md, docs/docs/1.4.x/quickstart/kubernetes.md, docs/docs/1.4.x/quickstart/universal.md, docs/docs/1.5.x/quickstart/kubernetes.md, docs/docs/1.5.x/quickstart/universal.md, docs/docs/1.6.x/quickstart/kubernetes.md, docs/docs/1.6.x/quickstart/universal.md, docs/docs/1.7.x/quickstart/kubernetes.md, docs/docs/1.7.x/quickstart/universal.md, docs/docs/1.8.x/quickstart/kubernetes.md, docs/docs/1.8.x/quickstart/universal.md, docs/docs/dev/quickstart/kubernetes.md, docs/docs/dev/quickstart/universal.md
This PR solves problem of duplication (it's seems duplicate at first) of Explore Kuma section 
SCREENSHOT-
=> Universal/Kubernetes "Explore section" were looking duplicate at first

docs/.vuepress/_snippets/install_os.md
Removes some unintentional whitespace.
=> chore: removes whitespace from code block

docs/docs/dev/policies/matching.md, docs/docs/dev/policies/mesh-trace.md, docs/docs/dev/sidebar.json
Closes https://github.com/kumahq/kuma-website/issues/1017
=> feat(kumacp): mesh trace docs

docs/docs/1.7.x/policies/health-check.md, docs/docs/1.8.x/policies/health-check.md, docs/docs/dev/policies/health-check.md
Signed-off-by: Alan Wang <ranwang@alauda.io>
fix health check tip, written as Circuit Breaker
=> fix: health check tip

app/preview.sh, jekyll.yml
Re-add missing preview.sh file
=> Add missing preview.sh file

app/_plugins/filters/indent_filter.rb, app/_plugins/tags/tabs/template.erb, app/docs/1.5.x/security/zoneegress-auth.md, app/docs/1.6.x/security/zoneegress-auth.md, app/docs/1.7.x/security/zoneegress-auth.md, app/docs/1.8.x/security/zoneegress-auth.md, app/docs/dev/security/zoneegress-auth.md
Tabbed content within an ordered list needs to use the `indent` filter to render correctly.
=> Fix nested tabs on zoneegress-auth

app/_plugins/generators/sitemap.rb, app/robots.txt, app/sitemap.xml, jekyll.yml
Add missing `sitemap.xml` and `robots.txt`
=> Add sitemap.xml and robots.txt

app/_includes/snippets/install_kumactl.md
=> Replace missed $page.latestVersion

labels.yml
=> add label for infra content

app/_assets/styles/prismjs/prism-vs.scss
Align line numbers with code in code blocks
Fixes https://github.com/kumahq/kuma-website/issues/1098
=> Fix line-numbers in code blocks

app/_data/docs_nav_kuma_1.7.x.yml, app/_data/docs_nav_kuma_1.8.x.yml, app/_data/docs_nav_kuma_dev.yml, app/docs/1.7.x/documentation/requirements.md, app/docs/1.8.x/documentation/requirements.md, app/docs/dev/documentation/requirements.md
=> docs(dp): add section on how to resize kuma-sidecar containers on Kubernetes

app/docs/1.5.x/policies/mesh-gateway.md, app/docs/1.6.x/policies/mesh-gateway.md, app/docs/1.7.x/policies/mesh-gateway.md, app/docs/1.8.x/policies/mesh-gateway.md, app/docs/dev/policies/mesh-gateway.md
=> docs(meshgateway): fix TLS certificates config

app/_assets/entrypoints/application.js, app/_layouts/page.html, package.json, yarn.lock
Configure it so that it applies to h1, ..., h6 and similar look and feel as before
Fixes #1100
https://user-images.githubusercontent.com/715229/199064363-d74633b0-c4ea-459e-94c8-e1fb3f0ed13b.mov
=> Add anchor-js

app/docs/dev/policies/traffic-metrics.md, app/docs/dev/security/certificates.md
=> add docs for MADS TLS

app/docs/dev/installation/docker.md, app/docs/dev/quickstart/universal.md, app/docs/dev/security/api-server-auth.md
This will be backported to other versions once we agree on the PR (it basically gets approved).
Closes https://github.com/kumahq/kuma-website/issues/644
=> feat(kumacp): add info about authentication in docker container

app/_data/docs_nav_kuma_dev.yml, app/docs/dev/policies/general-notes-about-kuma-policies.md, app/docs/dev/policies/how-kuma-chooses-the-right-policy-to-apply.md, app/docs/dev/policies/introduction.md, app/docs/dev/policies/meshaccesslog.md, app/docs/dev/policies/meshtrace.md, app/docs/dev/policies/targetref.md
=> update general targetRef policy docs

app/docs/1.3.x/security/certificates.md, app/docs/1.4.x/security/api-server-auth.md, app/docs/1.4.x/security/dp-auth.md, app/docs/1.4.x/security/zone-ingress-auth.md, app/docs/1.5.x/networking/dns-cp.md, app/docs/1.5.x/networking/transparent-proxying.md, app/docs/1.5.x/security/api-server-auth.md, app/docs/1.5.x/security/dp-auth.md, app/docs/1.5.x/security/zone-ingress-auth.md, app/docs/1.6.x/networking/dns-cp.md, app/docs/1.6.x/networking/transparent-proxying.md, app/docs/1.6.x/security/api-server-auth.md, app/docs/1.6.x/security/dp-auth.md, app/docs/1.6.x/security/zone-ingress-auth.md, app/docs/1.7.x/networking/transparent-proxying.md, app/docs/1.7.x/security/api-server-auth.md, app/docs/1.7.x/security/dp-auth.md, app/docs/1.7.x/security/zone-ingress-auth.md, app/docs/1.8.x/networking/transparent-proxying.md, app/docs/1.8.x/security/api-server-auth.md, app/docs/1.8.x/security/dp-auth.md, app/docs/1.8.x/security/zone-ingress-auth.md, app/docs/dev/explore/gateway-api.md, app/docs/dev/explore/gateway.md, app/docs/dev/networking/transparent-proxying.md, app/docs/dev/security/api-server-auth.md, app/docs/dev/security/dp-auth.md
Indent code snippets and content inside numbered lists
Fixes https://github.com/kumahq/kuma-website/issues/1127
=> Fix indentation in lists

app/_posts/2020-05-13-kuma-0-5-0.md, app/_posts/2020-09-10-multi-cluster-cloud.md
=> fix: remove images that don't exist anymore

app/_data/docs_nav_kuma_1.8.x.yml, app/_data/docs_nav_kuma_2.0.x.yml, app/_data/docs_nav_kuma_dev.yml, app/docs/1.6.x/policies/external-services.md, app/docs/1.7.x/policies/external-services.md, app/docs/1.8.x/policies/external-services.md, app/docs/2.0.x/policies/external-services.md, app/docs/dev/policies/external-services.md
Duplicate Debian entry in sidebar
Fix #1162
=> fix: sni and serverName in external-service

app/docs/2.0.x/deployments/multi-zone.md, app/docs/dev/deployments/multi-zone.md
[Rendered](https://deploy-preview-1164--kuma.netlify.app/docs/dev/deployments/multi-zone/#how-it-works)
=> docs(multi-zone): tweak explanation

app/docs/dev/reference/http-api.md
=> fix: improve http doc for inspect policy api

app/docs/2.0.x/explore/dpp-on-kubernetes.md, app/docs/dev/explore/dpp-on-kubernetes.md
[Before](https://kuma.io/docs/2.0.x/explore/dpp-on-kubernetes/#leaving-the-mesh) vs [after](https://deploy-preview-1173--kuma.netlify.app/docs/2.0.x/explore/dpp-on-kubernetes/#leaving-the-mesh)
=> docs(dpp-on-kubernetes): fix formatting

app/_data/docs_nav_kuma_dev.yml, app/docs/1.7.x/policies/health-check.md, app/docs/1.8.x/policies/health-check.md, app/docs/2.0.x/policies/health-check.md, app/docs/dev/policies/health-check.md, app/docs/dev/policies/introduction.md, app/docs/dev/policies/meshhealthcheck.md
closes #1174 
> Changelog: feat(policy): mesh health check
This PR adds docs for new policy MeshHealthCheck.
I've described my concerns with inconsistencies of the policies docs in this issue: https://github.com/kumahq/kuma-website/issues/1183 .
=> docs(policies): mesh health check docs

app/docs/dev/policies/meshhealthcheck.md
Update doc according to the latest changes in MeshHealthCheck policy.
=> docs: update meshhealthcheck

app/_data/docs_nav_kuma_dev.yml, app/_src/policies/introduction.md, app/_src/policies/meshtimeout.md
=> docs(meshtimeout) Add docs for MeshTimeout policy

app/_data/docs_nav_kuma_dev.yml, app/_src/policies/introduction.md, app/_src/policies/meshcircuitbreaker.md, app/_src/policies/meshhealthcheck.md
Add MeshCircuitBreaker policy docs
Closes: https://github.com/kumahq/kuma-website/issues/1175
Rendered: https://deploy-preview-1214--kuma.netlify.app/docs/dev/policies/meshcircuitbreaker/
=> docs: add MeshCircuitBreaker docs

app/_src/policies/meshtimeout.md
=> docs(meshtimeout) add note about wrong defaults

app/_src/policies/meshtrafficpermission.md
=> fix(meshtrafficpermission): correct case in constants

app/_data/versions.yml
=> fix: unrelease 2.1.x as it's not really out yet

app/_assets/javascripts/search.js
=> fix(search): add 10 results in search

app/_src/networking/networking.md
=> docs: intercp mention

CONTRIBUTING.md, README.md
Update contributing guides with a section about running the site locally
=> Update contributing guides with a section about running the site locally

app/_posts/2022-12-20-policy.md
change gep link because k8s changed the location
=> chore(links): change gep link because k8s changed the location

app/installer.sh
In preview and from 2.2.0 we changed packages location and build a unique linux package. This adapts installer.sh to get these at the right location
=> feat(installer.sh): update installer to use new packages

app/_posts/2020-10-07-announce-maintainer-austince.md
[https://konghq.com/conferences/kong-summit](https://konghq.com/conferences/kong-summit)) is returning 500. Changing the link to be a link to youtube recording.
=> fix(blog): fix blog entry linking to a presentation

app/_src/production/cp-deployment/multi-zone.md
Preview: https://deploy-preview-1280--kuma.netlify.app/docs/dev/production/cp-deployment/multi-zone/#set-up-the-global-control-plane
closes https://github.com/kumahq/kuma-website/issues/1231
=> feat(deployment): document new universal on kubernetes deployment option

app/_src/production/cp-deployment/multi-zone.md
=> fix(docs): identation of cmd

app/_src/production/cp-deployment/stand-alone.md
=> fix(docs): deploy standalone cp links to auth

app/installer.sh
Fix https://github.com/Kong/kong-mesh/issues/3152
=> fix(installer.sh): make preview work correctly

app/_src/explore/gateway.md
Docs for https://github.com/kumahq/kuma/pull/6388
=> Meshgateway new docs

app/_data/docs_nav_kuma_2.2.x.yml, app/_data/docs_nav_kuma_dev.yml, app/_src/policies/meshloadbalancingstrategy.md
[Rendered](https://github.com/kumahq/kuma-website/blob/fe8a35d66bdb7318c38cf545bf6eaafa1af4e7f3/app/_src/policies/meshloadbalancingstrategy.md)
=> docs(policy): add a new page for MeshLoadBalancingStrategy

.github/workflows/ci.yml, Gemfile, jekyll-kuma-plugins/.gitignore, jekyll-kuma-plugins/.rspec, jekyll-kuma-plugins/Gemfile, jekyll-kuma-plugins/Gemfile.lock, jekyll-kuma-plugins/README.md, jekyll-kuma-plugins/jekyll-kuma-plugins.gemspec, jekyll-kuma-plugins/lib/jekyll-kuma-plugins.rb, jekyll-kuma-plugins/lib/jekyll/kuma-plugins.rb, jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/test.rb, jekyll-kuma-plugins/lib/jekyll/kuma-plugins/version.rb, jekyll-kuma-plugins/sig/jekyll/kuma-plugins/plugins.rbs, jekyll-kuma-plugins/spec/jekyll/kuma-plugins/liquid/tags/test_spec.rb, jekyll-kuma-plugins/spec/jekyll/kuma-plugins/plugins_spec.rb, jekyll-kuma-plugins/spec/spec_helper.rb
The goal is to move #1289 and #1290 inside this gem
=> feat: add a gemfile for reusable plugins

app/_plugins/generators/navigation_links.rb, app/_plugins/generators/versions.rb, app/_src/production/install-kumactl.md, jekyll-dev.yml, jekyll.yml
This makes things simpler in inherited docs
=> fix: kumactl install docs should be more generic

app/_src/policies/meshaccesslog.md
Change according to the https://github.com/kumahq/kuma/pull/6676
=> docs(policy): add field "type" for MeshAccessLog

app/preview.sh
Set a correct `$PRODUCT_NAME` default value in `preview.sh` script
=> fix(script): fix PRODUCT_NAME default for preview.sh

app/_src/policies/meshhttproute.md
=> docs(MeshHTTPRoute): fix Prefix -> PathPrefix

app/_src/policies/meshtrace.md
https://github.com/kumahq/kuma/pull/6679
=> docs(policy): add field "type" for MeshTrace

app/_data/docs_nav_kuma_dev.yml, app/_src/policies/meshtcproute.md
Initial version of `MeshTCPRoute` documentation
xref: https://github.com/kumahq/kuma/issues/6787
=> docs(policies): add MeshTCPRoute docs

app/_src/production/install-kumactl.md, jekyll.yml
=> fix(kumactl): fix installation instructions

app/_src/documentation/configuration.md, app/_src/explore/gateway-api.md, app/_src/production/cp-deployment/zone-ingress.md, app/_src/production/cp-deployment/zoneegress.md, app/_src/production/dp-config/cni.md, app/_src/production/secure-deployment/api-server-auth.md, app/_src/production/secure-deployment/certificates.md
Adds missing HELM prefix.
This PR https://github.com/kumahq/kuma-website/pull/1354 covers multizone
=> docs(*): add missing HELM prefix

app/_src/policies/meshhttproute.md
Fix https://github.com/kumahq/kuma-website/issues/1332, fix https://github.com/kumahq/kuma-website/issues/1317
=> docs(policy): request mirror

Gemfile.lock, app/_assets/javascripts/form.js, package.json, yarn.lock
1. Update dev dependencies (which also removes the security vulnerability)
2. Remove unused axios dependency
=> chore: update dependencies

app/_src/reference/kubernetes-annotations.md
Docs for https://github.com/kumahq/kuma/pull/7070
=> feat(annotations): add init-first

app/_src/policies/external-services.md
=> fix: remove https in external-service protocol

app/_includes/footer.html
=> chore: add trademark usage to footer

app/_src/production/dp-config/cni.md
Add Azure CNI Overlay instructions to CNI docs
=> docs(cni): add Azure CNI Overlay instructions to cni docs

app/_src/production/dp-config/dpp-on-kubernetes.md
=> feat: add note about accessing headless service

app/_layouts/default.html, jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/jsonschema.rb
Avoids having to set the dependency in child repo
=> fix: move showdown in the plugins

app/_src/explore/cli.md, app/_src/policies/general-notes-about-kuma-policies.md, app/_src/policies/how-kuma-chooses-the-right-policy-to-apply.md, app/_src/policies/introduction.md, app/_src/policies/mesh-gateway-route.md, app/_src/policies/mesh-gateway.md, app/_src/policies/meshaccesslog.md, app/_src/policies/meshcircuitbreaker.md, app/_src/policies/meshfaultinjection.md, app/_src/policies/meshhealthcheck.md, app/_src/policies/meshhttproute.md, app/_src/policies/meshloadbalancingstrategy.md, app/_src/policies/meshratelimit.md, app/_src/policies/meshretry.md, app/_src/policies/meshtcproute.md, app/_src/policies/meshtimeout.md, app/_src/policies/meshtrace.md, app/_src/policies/meshtrafficpermission.md, app/_src/production/cp-deployment/multi-zone.md, app/_src/production/cp-deployment/stand-alone.md, app/_src/production/dp-config/dpp.md, app/_src/production/index.md, app/docs/2.0.x/policies/general-notes-about-kuma-policies.md, app/docs/2.0.x/policies/how-kuma-chooses-the-right-policy-to-apply.md, app/docs/2.0.x/policies/introduction.md, app/docs/2.0.x/policies/meshaccesslog.md, app/docs/2.0.x/policies/meshtrace.md, app/docs/2.0.x/policies/meshtrafficpermission.md, jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/embed.rb
Also add the possibility to redact URLs from the page
=> chore: fix links to make them work well in docs.konghq.com

app/_src/introduction/how-kuma-works.md, app/_src/networking/service-discovery.md, app/_src/production/cp-deployment/multi-zone.md, app/_src/production/dp-config/transparent-proxying.md, app/_src/production/mesh.md, app/_src/production/secure-deployment/api-server-auth.md
Some plugin down in docs.konghq.com gets upset otherwise
=> fix: always put ( closed to link when doing conditional rendering

Makefile, app/_includes/version_alert.html
=> fix: don't display alert on the latest versions of the doc

app/_src/policies/virtual-outbound.md
Clarify cross-zone limitation that is also lifted in upcoming Kuma version
=> docs(policies): clarify VirtualOutbound limitation

app/_src/reference/kubernetes-annotations.md
=> fix: annotation typo

app/_common_redirects
This was a broken link from the GUI
=> fix(redirect): correct TrafficPermission redirects

app/_src/policies/retry.md
=> fix(retry): correct baseDuration to baseInterval

app/_src/production/dp-config/dpp-on-kubernetes.md, app/_src/reference/kubernetes-annotations.md
=> fix(annotations): remove reference to injection annotation

app/_src/production/upgrades-tuning/fine-tuning.md
In 2.3.x version we have added a couple of configuration option that could help with performance issues on big k8s cluster
=> feat: extend kubernetes perf tuning section

app/_posts/2023-08-28-kuma-2-4-0.md
=> fix: blog post cleanup

app/_src/explore/gateway-api.md, app/_src/policies/meshhttproute.md
Increases the chances users remember this, it's hard to debug ATM
=> docs(routing): add note about appProtocol

app/_src/production/dp-config/cni.md
=> fix(cni): add quotes around bool env var

app/_src/documentation/configuration.md
=> reword warning for in memory store

.github/styles/Vocab/Base/accept.txt, .github/workflows/ci.yml, app/_data/docs_nav_kuma_2.4.x.yml, app/_data/docs_nav_kuma_dev.yml, app/_src/production/cp-deployment/kubernetes.md, jekyll-dev.yml, jekyll.yml
=> feat: add kubernetes docs with diverse info

app/_src/policies/meshtimeout.md
it was not rendering correctly
=> fix: example of MeshHTTPRoute with MeshTimeout

app/_src/production/cp-deployment/multi-zone.md
=> fix: add prefix to helm values

app/_src/introduction/kuma-requirements.md
=> fix(k8s): correct max k8s version

app/_assets/styles/custom/base/_structure.scss, app/_assets/styles/custom/components/_sidebar.scss
=> fix: sidebar search overlay being cut-off

app/_src/production/cp-deployment/multi-zone.md, app/_src/production/cp-deployment/stand-alone.md, app/_src/production/deployment/multi-zone.md, app/_src/production/deployment/stand-alone.md, app/docs/1.4.x/deployments/multi-zone.md, app/docs/1.5.x/deployments/multi-zone.md, app/docs/1.6.x/deployments/multi-zone.md, app/docs/1.7.x/deployments/multi-zone.md, app/docs/1.8.x/deployments/multi-zone.md, app/docs/1.8.x/deployments/stand-alone.md, app/docs/2.0.x/deployments/multi-zone.md, app/docs/2.0.x/deployments/stand-alone.md, jekyll-dev.yml, jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/cpinstall.rb, jekyll.yml
- Yes
- Yes
This fixes https://github.com/kumahq/kuma-website/issues/1509
=> Improvements to doc on control plane installation

app/_src/policies/traffic-metrics.md
=> fix: traffic-metrics example

.github/workflows/ci.yml, app/_src/production/dp-config/transparent-proxying.md
IMHO comments are better because
* You can resolve it
* You can discuss about it
* Diff with resolved comments is easier to review
=> change vale reporter

app/_src/production/cp-deployment/multi-zone.md
Removing duplicated line "In this example the value is 35.226.196.103:5685. You pass this as the value of <global-kds-address> when you set up the zone control planes."
=> Remove duplicated line

app/_src/policies/meshtcproute.md
Closes https://github.com/kumahq/kuma-website/issues/1565
=> docs(MeshTCPRoute): mention missing cross-zone support

app/_includes/snippets/install_kumactl.md, app/_src/production/install-kumactl.md
added export so PATH update is not limited to current session
```yes```
```yes```
=> add export to path

app/_src/policies/virtual-outbound.md
=> fix(virtualOutbound): fix typo in example

app/_includes/distribution_dropdown.html
=> docs(website): change button order

app/_src/policies/meshloadbalancingstrategy.md
=> fix(meshloadbalancingstrategy): expand explanation of failover

app/_data/docs_nav_kuma_dev.yml, app/_src/guides/federate.md, app/_src/quickstart/kubernetes-demo.md
Guide to point how to federate a zone into multizone deployment
=> docs(guides) federation

app/_src/policies/targetref.md
=> docs(targetRef): added information about proxyTypes

app/_src/quickstart/kubernetes-demo.md
=> fix(demo): changed name of the policy

app/_src/policies/meshtimeout.md
=> docs(meshtimeout): added new configuration option, and proxyTypes example

app/_data/docs_nav_kuma_dev.yml, app/_src/documentation/health.md
Update [Monitor & Manage / Dataplane Health](https://kuma.io/docs/dev/documentation/health/#dataplane-health) section with new policies
Relates to: https://github.com/kumahq/kuma-website/issues/1599
=> docs(dataplane-health): update with new policies

app/_src/policies/meshtimeout.md
* Fix rendering of wrong `Timeouts explained` header indentation
* Fixes of small style/ort mistakes
* Add missing <code>```</code>
=> docs(MeshTimeout): small style fixes + render fix

app/_src/policies/circuit-breaker.md, app/_src/policies/health-check.md, app/_src/policies/retry.md, app/_src/policies/timeout.md
=> docs(policies): added information about TrafficRoute

app/_layouts/default.html, app/_src/index.md, app/features/index.md, app/index.md
=> feat: add meshMetric in the features list

app/_src/guides/federate.md, app/_src/quickstart/kubernetes-demo.md
=> fix(quickstart): use the variable for the helm chart

.github/workflows/ci.yml, app/installer.sh
Behavior was changed at some point, [breaking kong-mesh-ecs](https://github.com/Kong/kong-mesh-ecs/actions/runs/7881728764/job/21505818554#step:6:1).
=> fix(installer.sh): --print-version with preview versions

app/_data/docs_nav_kuma_2.6.x.yml, app/_data/docs_nav_kuma_dev.yml, app/_src/guides/builtin-gateway.md, app/_src/quickstart/kubernetes-demo.md, app/_src/using-mesh/managing-ingress-traffic/builtin.md
=> feat(guides): add meshgateway guide

app/_data/docs_nav_kuma_2.6.x.yml, app/_data/docs_nav_kuma_dev.yml, app/_src/guides/gateway-builtin.md, app/_src/guides/gateway-delegated.md, app/_src/quickstart/kubernetes-demo.md, app/_src/using-mesh/managing-ingress-traffic/builtin.md, app/_src/using-mesh/managing-ingress-traffic/delegated.md
=> feat(guides): add kong delegated gateway guide

.github/workflows/ci.yml
It was using an exact match not a prefix
=> ci(check-links): skip kuma pull requests correctly

app/_src/policies/meshtcproute.md
=> docs(meshtcproute): added gateway with listener tags support

app/_src/policies/meshaccesslog.md, app/_src/policies/meshcircuitbreaker.md, app/_src/policies/meshfaultinjection.md, app/_src/policies/meshhealthcheck.md, app/_src/policies/meshhttproute.md, app/_src/policies/meshloadbalancingstrategy.md, app/_src/policies/meshmetric.md, app/_src/policies/meshproxypatch.md, app/_src/policies/meshratelimit.md, app/_src/policies/meshretry.md, app/_src/policies/meshtcproute.md, app/_src/policies/meshtimeout.md, app/_src/policies/meshtrace.md, app/_src/policies/meshtrafficpermission.md
Fix: https://github.com/kumahq/kuma-website/issues/1638
=> docs(policies): added policy support table for delegated gateway

app/_src/policies/meshmetric.md
in https://github.com/kumahq/kuma/pull/9406 we implemented the "sidecar" support
=> feat(meshmetric): remove sidecar limitation for future release

app/_src/policies/meshmetric.md
Fixes: #1676 
Removed MeshMetric OpenTelemtry limitations from docs, and added description on how to push metrics from app to OpenTelemetry collector
=> feat(policy): improve meshmetric docs for opentelemetry backend

app/_src/production/cp-deployment/kubernetes.md
=> docs(deployment): argo rollouts

app/_src/policies/meshmetric.md
Rendered:
- https://deploy-preview-1713--kuma.netlify.app/docs/2.6.x/policies/meshmetric/#sidecar
- https://deploy-preview-1713--kuma.netlify.app/docs/dev/policies/meshmetric/#sidecar
Add docs for https://github.com/kumahq/kuma/pull/9624
closes https://github.com/kumahq/kuma-website/issues/1700
=> docs(meshmetric): add profiles docs

app/_src/production/dp-config/dpp-on-kubernetes.md
[Rendered](https://deploy-preview-1731--kuma.netlify.app/docs/dev/production/dp-config/dpp-on-kubernetes/#lifecycle)
=> feat(k8s): add sidecar feature

app/_src/policies/applying-policies.md
Docs for https://github.com/kumahq/kuma/pull/9887
Fix https://github.com/kumahq/kuma-website/issues/1728
=> feat(docs): shadow mode for resources

app/_src/policies/meshloadbalancingstrategy.md
Add more information about MeshLoadbalancingStrategy and zone proxies. Add a workaround.
Fix #1440
=> docs(policies): zone proxies and meshloadbalancingstrategy

app/_src/using-mesh/managing-ingress-traffic/builtin.md, jekyll.yml
closes https://github.com/kumahq/kuma-website/issues/1714
=> docs(meshgateway): add example of unmanaged Deployment/Service for MeshGateway

app/_data/docs_nav_kuma_2.7.x.yml, app/_src/guides/transition-to-the-new-policies.md
Fix https://github.com/kumahq/kuma-website/issues/1729
=> feat(guides): transition to the new policies

app/_src/introduction/architecture.md, app/_src/introduction/overview-of-kuma.md, app/_src/production/dp-config/dpp-on-kubernetes.md, app/_src/quickstart/kubernetes-demo.md, app/docs/1.2.x/overview/what-is-kuma.md, app/docs/1.3.x/overview/what-is-kuma.md, app/docs/1.4.x/overview/what-is-kuma.md, app/docs/1.5.x/overview/what-is-kuma.md, app/docs/1.6.x/introduction/what-is-kuma.md, app/docs/1.7.x/introduction/what-is-kuma.md, app/docs/1.8.x/explore/overview.md, app/docs/1.8.x/introduction/what-is-kuma.md, app/docs/2.0.x/explore/overview.md, app/docs/2.0.x/introduction/what-is-kuma.md
Fix some document typos
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits)- Yes
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?- Yes
=> fix(docs): fix some typos

app/_src/introduction/how-kuma-works.md
This was a great doc for understanding more about the Service Mesh, but I noticed a few minor grammar/formulation points to suggest modifications to.
=> fix: minor suggestions for modifications to "how mesh works"

app/_src/introduction/overview-of-kuma.md
close https://github.com/kumahq/kuma-website/issues/1764
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)? - yes
=> fix bold font

.github/workflows/ci.yml
Remove CI step with hardcoded preview version, as we are basically testing this in other steps
=> chore(ci): remove installer test for hardcoded preview version

app/_src/introduction/kuma-requirements.md
Fix #1776
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> docs: update Envoy requirements

app/_src/networking/service-discovery.md
=> fix(service-discovery): fix bad link

app/_src/guides/gateway-delegated.md
close #1770 
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)? - yes
=> fix(docs): supplement kong gateway proxy ip variable

app/_data/docs_nav_kuma_dev.yml, app/_src/networking/non-mesh-traffic.md, app/_src/policies/meshpassthrough.md
=> feat(meshpassthrough): new feature documentation

app/_src/policies/meshmetric.md
=> fix(meshmetric): add missing fields

app/_src/policies/meshpassthrough.md
xref https://github.com/kumahq/kuma/pull/10532
=> feat(meshpassthrough): add proxy types

app/_src/policies/meshpassthrough.md
https://github.com/kumahq/kuma/pull/10576/files
=> fix(meshpassthrough): changed enabled to passthroughMode

app/_data/docs_nav_kuma_2.1.x.yml, app/_data/docs_nav_kuma_2.2.x.yml, app/_data/docs_nav_kuma_2.3.x.yml, app/_data/docs_nav_kuma_2.4.x.yml, app/_data/docs_nav_kuma_2.5.x.yml, app/_data/docs_nav_kuma_2.6.x.yml, app/_data/docs_nav_kuma_2.7.x.yml, app/_data/docs_nav_kuma_2.8.x.yml, app/_data/docs_nav_kuma_dev.yml, app/_src/explore/observability.md
Closes https://github.com/kumahq/kuma-website/issues/1397
=> docs(observability): mention CP opentelemetry tracing

app/_src/introduction/kuma-requirements.md
=> docs: fix for removed circleci file.

app/_src/guides/migration-to-the-new-policies.md
Closes https://github.com/kumahq/kuma/issues/8923
=> docs(policies): add migration of MeshGatewayRoute to Mesh*Route

app/_src/production/cp-deployment/zone-ingress.md
=> fix(zone-ingress): use same port in zoneIngress example

app/_src/reference/kubernetes-annotations.md
fixes https://github.com/kumahq/kuma-website/issues/1832
* Yes
* Yes
=> docs(kuma-dp): add the doc for enabling the envoy logs on dataplane proxies

app/_src/production/dp-config/dpp-on-universal.md
Some users were confused that without transparent proxy their app is still available. We clarify here and offer options for user to potentially hide the original service
=> fix(universal-dpp): make it clearer that folks can bypass sidecar

package.json, yarn.lock
closes https://github.com/kumahq/kuma-website/issues/1874
=> chore(update): update netlify-cli to v17.34.1

app/_src/production/upgrades-tuning/fine-tuning.md
=> fix(production): available tags for autoreachable services

app/_src/production/secure-deployment/api-server-auth.md
Fixes https://github.com/kumahq/kuma-website/issues/1860
Yes.
Yes.
Preview link: https://deploy-preview-1879--kuma.netlify.app/docs/2.8.x/production/secure-deployment/api-server-auth/#authentication-with-the-api-server
=> fix(auth): format namespace in api server auth

app/_src/production/dp-config/dpp-on-universal.md
=> docs(universal): added tip about serviceAddress

app/_src/policies/service-health-probes.md, app/_src/reference/kubernetes-annotations.md
fixes https://github.com/kumahq/kuma-website/issues/1887
Yes
Yes
=> feat(app-probe-proxy): add document for application probe proxy

app/_src/production/upgrades-tuning/upgrades.md
=> docs(upgrade): be more specific on kuma-dp upgrade docs

app/_data/docs_nav_kuma_dev.yml, app/_src/policies/meshpassthrough.md, app/_src/policies/meshtls.md, app/_src/policies/mutual-tls.md
rendered: https://deploy-preview-1893--kuma.netlify.app/docs/dev/policies/meshtls/
closes https://github.com/kumahq/kuma-website/issues/1890
=> feat(meshtls): initial docs

app/_src/policies/meshaccesslog.md, app/_src/policies/meshhttproute.md, app/_src/policies/meshretry.md, app/_src/policies/meshtcproute.md, app/_src/policies/meshtimeout.md
fix: https://github.com/kumahq/kuma-website/issues/1891
=> docs(meshexternalservice): added target ref support to policies

app/_assets/javascripts/tabs.js, app/_plugins/tags/tabs/template.erb
Mark all tabs with the same slug as `active`.
https://github.com/user-attachments/assets/f4c6a15e-1135-4442-9837-5ae1b8863a15
=> Activate all tabs that match the current tab's slug

package.json, yarn.lock
=> chore(deps): manually bump netlify-cli to 17.36.4

app/_src/networking/meshservice.md
Part of https://github.com/kumahq/kuma-website/issues/1933
=> docs(MeshService): document generation on universal

app/_src/networking/meshservice.md
Part of https://github.com/kumahq/kuma-website/issues/1936
=> docs(MeshService): add information about targeting

.github/dependabot.yml
Less warnings and annotation noise in the runs
=> ci(dependabot): add config for GH workflows

app/_src/policies/introduction.md
See https://github.com/kumahq/kuma-website/issues/1892
=> docs(targetRef): fix tab order, remove unnecessary note

app/_src/production/index.md, app/_src/production/use-mesh.md
Add missing links, more links and fix inconsistent capitalization and hyphenation.
=> docs(production): improve formatting and style

app/_src/guides/migration-to-the-new-policies.md
Part of https://github.com/kumahq/kuma-website/issues/1961
=> docs(migration): dynamically get Dataplane name

.github/styles/config/vocabularies/Base/accept.txt, app/_src/policies/introduction.md, app/_src/policies/meshhttproute.md, app/_src/policies/meshtcproute.md
Closes https://github.com/kumahq/kuma-website/issues/1752
[Rendered](https://deploy-preview-2002--kuma.netlify.app/docs/dev/policies/introduction/#targeting-gateways)
=> docs(policies): add explanation of MeshGateway listener attachment and routes

app/_src/community/contribute-to-kuma.md
Fixing typo and added correct links to contributing guides for specific projects
=> fix(contribute): fix typos and add correct links to contributing guides

app/_src/policies/meshhttproute.md, app/_src/policies/meshtcproute.md
Fix https://github.com/kumahq/kuma-website/issues/1918
=> docs(policies): interactions with traffic route

app/_data/docs_nav_kuma_2.9.x.yml, app/_data/docs_nav_kuma_dev.yml
I think that lexicographical order makes it easier to find policies in the navbar
=> feat(nav): order new policies lexicographically in navbar

app/_src/guides/consumer-producer-policies.md
a producer policy is created in the same namespace 
=> docs(guide): fix producer policy definition

app/_src/guides/otel-metrics.md
Our guide was outdated, and caused issues with otel
=> feat(guides): update otel collector guide to work with newest otel collector

app/_src/policies/meshpassthrough.md
Since 2.9.x we support delegated gateway
=> docs(meshpassthrough): update support for gateway

package.json, yarn.lock
Use `resolutions` to upgrade `cookie`
=> chore: upgrade cookie with resolutions

.github/workflows/ci.yml
it was failing and we know the file is there
=> ci(checklinks): skip changelog from checklinks

app/_src/introduction/install.md, app/_src/quickstart/universal-demo.md
There was a bug in the logic for installer which was causing a 404
=> fix installer

app/_assets/javascripts/tabs.js
We do not automatically sync changes to tabs.js to https://github.com/Kong/docs.konghq.com/blob/main/app/_assets/javascripts/tabs.js
=> chore(tabs): add warning about syncing tabs.js

app/_src/policies/meshfaultinjection.md, app/_src/policies/meshratelimit.md
Since 2.6 we need to add proxyTypes for from policies
=> docs(policies): added missing proxyTypes to policies

.github/workflows/ci.yml
fix https://github.com/kumahq/kuma-website/issues/2156
=> chore(links): set accept-language

package.json, yarn.lock
Dependabot has some issues so I've upgraded manually
=> chore(deps): bump netlify-cli from 17.36.4 to 18.0.4

app/_src/guides/federate.md, app/_src/guides/gateway-api.md, app/_src/guides/gateway-builtin.md, app/_src/guides/gateway-delegated.md, app/_src/guides/otel-metrics.md, app/_src/guides/progressively-rolling-in-strict-mtls.md, app/_src/production/mesh.md, app/_src/quickstart/kubernetes-demo.md, app/_src/quickstart/universal-demo.md
We need to update our docs after adding new kind Dataplane
=> feat(dataplane): update guides and quickstart to use new kind Dataplane

app/_src/production/secure-deployment/secrets.md
=> feat(secret): describe the syncing behavior of secret

app/_src/policies/introduction.md
There was a usage of `new` and we were just repeating 3 times the same thing with different words.
=> chore(policies): minor tweak to shadow mode intro

app/_src/policies/meshaccesslog.md
Fix https://github.com/kumahq/kuma-website/issues/2133
=> docs(meshaccesslog): update with 'rules'

app/_src/policies/meshtls.md
Fix https://github.com/kumahq/kuma-website/issues/2134
=> docs(meshtls): update with 'rules'

app/_src/policies/meshratelimit.md
Fix https://github.com/kumahq/kuma-website/issues/2135
=> docs(meshratelimit): update with 'rules'

app/_src/policies/meshtimeout.md
Fix https://github.com/kumahq/kuma-website/issues/2132
=> docs(meshtimeout): update with 'rules'

jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/policyyaml.rb, spec/fixtures/mhr-port_edition.golden.html
As part of https://github.com/Kong/kong-mesh/issues/7207 we would like to see the resources in form of Terraform resource.
**Questions**: 
1. Should we show this only on 2.10 onwards or some other version?
2. Is it ok that I only use "meshservice" version of the resource?
This is now guarded with `edition != 'kuma'` but if uncommented this is how it looks like:
```
resource "konnect_mesh_access_log" "frontend_to_backend" {
type = "MeshAccessLog"
name = "frontend-to-backend"
mesh = "default"
spec = {
target_ref = {
kind = "Dataplane"
labels = {
app = "frontend"
version = "canary"
}
}
to = [
{
target_ref = {
kind = "MeshService"
name = "backend"
section_name = "http"
}
default = {
backends = [
{
type = "File"
file = {
path = "/dev/stdout"
}
}
]
}
}
]
}
}
```
Example resource worked fine: …
=> feat(policyyaml): add Terraform tab

app/_src/production/upgrades-tuning/fine-tuning.md
=> feat(dataplane): update fine-tuning section to include new Dataplane kind and remove deprecations

jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/policyyaml.rb
did not use the new variable for condition
=> feat(tf): fix condition

app/_src/policies/meshcircuitbreaker.md
Fix https://github.com/kumahq/kuma-website/issues/2166
=> docs(meshcircuitbreaker): update with `rules`

app/_src/quickstart/universal-docker-demo.md
In some cases these links were incorrect
---
=> fix(quickstart/universal): fix installer links

app/_src/guides/otel-metrics.md
Fixes: https://github.com/kumahq/kuma-website/issues/2253
=> fix(guide): improve open telemetry guide

app/_src/guides/progressively-rolling-in-strict-mtls.md
Fixes: https://github.com/kumahq/kuma-website/issues/2254
=> fix(guide): improve progressively rolling strict mtls guide

jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/jsonschema.rb
=> fix(plugin): fix generation of all policies options

app/_src/policies/meshpassthrough.md
Added note about meshpassthrough and support for mysql
=> feat(meshpassthrough): added docs about mysql support

app/_src/guides/otel-metrics.md
=> feat(docs): Added instructions for dash0 OTEL

.github/workflows/ci.yml, .github/workflows/lifecycle.yml
so that https://github.com/kumahq/kuma-website/actions/runs/14078356156/job/39425515520#step:3:16 passes 
=> chore(deps): pin actions

app/_src/reference/kubernetes-annotations.md
Was included in 2.8 but condition was wrong
=> fix(labels): kuma.io/mesh was added in 2.8

app/_src/policies/meshcircuitbreaker.md
Fix #1953 
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?- yes
=> chore(docs): explain the envoy panic threshold for MeshCircuitBreaker

app/_src/production/upgrades-tuning/fine-tuning.md
=> fix(autoreachable): revert update on autoreachable services that does not work

app/_data/docs_nav_kuma_2.11.x.yml, app/_src/guides/consumer-producer-policies.md, app/_src/guides/federate-kv.md, app/_src/production/cp-deployment/single-zone.md, app/_src/production/deployment/single-zone.md, app/_src/quickstart/kubernetes-demo-kv.md
We need updated guide as we moved to kv demo
=> feat(guide): migrate federate guide to kv demo

app/_src/guides/otel-metrics.md
we need to update guide to use new demo
=> feat(guide): add quickstart tip to otel guide

app/_src/quickstart/kubernetes-demo-kv.md
fixing graph that is not rendering
=> fix: fix mermaid graph in new kube demo

app/_src/policies/meshtrafficpermission.md
fix: https://github.com/kumahq/kuma-website/issues/2281
=> docs(mtp): added note for not supporting MES

package.json, yarn.lock
Dependabot failed to update it https://github.com/kumahq/kuma-website/actions/runs/16464917988/job/46539843771
=> chore(deps): manually bump netlify-cli to 22.4.0

app/_src/policies/meshmetric.md
Closes https://github.com/kumahq/kuma-website/issues/2159
=> docs(meshmetric): change example to not be redundant

app/_src/guides/gateway-delegated-kv.md
Something changed (probably GW instructions) and the guide no longer worked.
=> guide(gw): update delegated gw guide

.github/styles/config/vocabularies/Base/accept.txt, app/_src/production/dp-config/cni.md
fixes https://github.com/kumahq/kuma-website/issues/2372
* yes
* yes
=> docs(cni): add CNI architecture docs

app/_src/production/dp-config/cni.md
closes https://github.com/kumahq/kuma-website/issues/2076
preview: https://deploy-preview-2388--kuma.netlify.app/docs/2.9.x/production/dp-config/cni/#installation
=> docs(cni): add dataplane v2 instructions

.github/workflows/ci.yml
update timeout for checking links
=> fix(ci): bump check links timeout

app/_src/policies/meshtrace.md
Closes https://github.com/kumahq/kuma-website/issues/2183
=> docs(meshtrace): add gw required tags

app/_src/guides/progressively-rolling-in-strict-mtls-kv.md
Small tweaks to guide for new demo 
=> fix(guide): small updated to MeshTLS guide
