setup-redirects/index.js

Using `.../docs/latest` will now always redirect to the latest version.
* https://feat-latest-version-redirect--kuma.netlify.com/docs/latest/
* https://feat-latest-version-redirect--kuma.netlify.com/docs/0.1.2/documentation/#universal-mode
**Note:** This is a redirect that is setup for Netlify, so it won't work locally.

feat(docs) new latest redirect splat

---

docs/.vuepress/theme/layouts/Layout.vue
docs/.vuepress/theme/styles/custom/base/_type-and-content.scss
docs/.vuepress/theme/styles/custom/config/_variables.scss
docs/.vuepress/theme/styles/prismjs/prism-ghcolors.scss
docs/.vuepress/theme/styles/prismjs/prism-vs.scss
docs/.vuepress/theme/styles/styles.scss
docs/.vuepress/theme/styles/vuepress-core/config.scss
package.json
yarn.lock

A newer version of VuePress allows for easier overriding of the code highlighting. I've implemented a light version:

VuePress upgrade and light code theme

---

docs/docs/0.1.0/policies/README.md
docs/docs/0.1.1/policies/README.md
docs/docs/0.1.2/policies/README.md
docs/docs/0.2.0/policies/README.md
docs/docs/0.2.1/policies/README.md
docs/docs/0.2.2/policies/README.md
docs/docs/draft/documentation/README.md
docs/docs/draft/policies/README.md

*  update configuration examples for `TrafficPermission` and `TrafficRoute` (`rules` field has been removed)
* update configuration examples for `ProxyTemplate` (to be in sync with actual implementation)
* fix invalid configuration examples
* update REST API examples

docs: update configuration examples for 0.3.0 release

---

docs/docs/draft/documentation/README.md

Is this enough? I think it's worth do describe UI with a screen or two once we've got it working in our release.

docs(readme) port on which Kuma GUI is exposed

---

docs/.vuepress/theme/global-components/Footer.vue

All footer links are now updated to match konghq.com, with the exception of "Documentation" under the "Resources" heading, which links to Kuma's docs page.

Footer link updates

---

bin/setup-redirects/index.js
docs/.vuepress/theme/components/custom/Community.vue
docs/.vuepress/theme/components/custom/RequestADemo.vue
docs/.vuepress/theme/components/custom/Shell.vue
docs/.vuepress/theme/layouts/Layout.vue
docs/newsletter/error.md
docs/newsletter/thank-you.md

Since Netlify doesn't play nice with Vue and throws 404 pages with URL queries, this change adds static thank you and failure pages for the newsletter form. this is a foolproof workaround that will work correctly with SalesForce Pardot.
- When redirecting back from the Pardot handler, URLs like `/?form_success=true` and `/?form_success=false` will send the user to a 404 page
- If you refresh these pages, the correct behavior occurs (the user is sent to the newsletter form on the homepage, and they are presented with a failure or success message below the form)
Netlify has methods for handling redirects but from my experience, nothing solved this issue. So the easiest solution is to create static pages on the site for both failed and successful submissions. The alternative is to change …

Newsletter Pardot Handler redirect static pages

---

docs/docs/0.1.2/installation/centos.md
docs/docs/0.1.2/installation/debian.md
docs/docs/0.1.2/installation/redhat.md
docs/docs/0.1.2/installation/ubuntu.md

Currently, all the downloadable tarballs referred to in the installation
documentation are amd64/x86_64 ones. This patch adds info about that in
the page titles in order for us who run e.g. Ubuntu/aarch64 and similar
Linux + non-PC HW systems to be mislead.
Change-Id: I9b59b1c8b20f6f66119e325650973ff02850f623
Signed-off-by: Joakim Roubert <joakimr@axis.com>

Add architecture info in installation pages

---

docs/docs/0.2.2/installation/centos.md
docs/docs/0.2.2/policies/applying-policies.md
docs/docs/0.3.0/policies/applying-policies.md
docs/docs/0.3.1/policies/applying-policies.md
docs/docs/0.3.2/overview/enabling-modernization.md
docs/docs/0.3.2/policies/README.md
docs/docs/0.3.2/policies/applying-policies.md
docs/docs/draft/policies/README.md
docs/docs/draft/policies/applying-policies.md

Fixed the listed 404s:
- https://kuma.io/docs/0.3.2/overview/enabling-modernization - Text: "Learn more"
- https://kuma.io/docs/0.3.2/documentation/ - Text: "kumactl"
This link needs to be reviewed and either removed or updated with the most recent page available from the Envoy website:
- https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/v2_overview - Text: xDS (found in the `/documentation/overview.md` file of each version)

404 error fixes

---

bin/setup-redirects/index.js

Added redirects that cover old root pages from the docs before the changes. Search engines are still holding onto some of these URLs, so this change covers those.
- `/docs/:version/policies/` => `/docs/:version/policies/introduction/`
- `/docs/:version/documentation/` => `/docs/:version/documentation/introduction/`
- `/docs/:version/overview/` => `/docs/:version/overview/what-is-kuma/`
- `/docs/:version/installation/` => `/docs/:version/installation/centos/` _(CentOS is the first one in the list which is why it was used here)_
- `/docs/:version/other/` => `/docs/:version/other/introduction/`

Old URL redirects

---

bin/setup-redirects/index.js

This is a small change to (2) redirects (`/docs` and `/install`) that Netlify recommended changes for in an email to users. Learn more [at this blog post](https://community.netlify.com/t/changed-behavior-in-redirects/10084/13). These redirects are now explicitly forced to align with the bugfix that Netlify recently made and to prevent any issues when the bugfix goes live on April 7, 2020.

Explicit force for Netlify redirects

---

docs/.vuepress/public/community-call-invite.ics
docs/.vuepress/theme/global-components/CommunityCallForm.vue
docs/.vuepress/theme/store/index.js

Added the agenda link and calendar invite (ICS file) to the Community Call form confirmation.
1. run `yarn docs:dev`
2. go to `http://localhost:8080/community/?form_success=true` (`?form_success=true` is the URL Salesforce will send the user back to after the form is submitted)
[Screenshot](https://share.getcloudapp.com/OAubbeQP)
You should see each link now in the confirmation the user is presented with after they've submitted the form.

Community call form confirmation updates

---

docs/docs/0.5.0/installation/amazonlinux.md
docs/docs/0.5.0/installation/docker.md
docs/docs/0.5.0/installation/openshift.md
docs/docs/0.5.0/quickstart/kubernetes.md
docs/docs/0.5.0/quickstart/universal.md

I fixed examples of `Mesh` resource and an example of the command to generate traffic on [the v0.5.0 docs](https://kuma.io/docs/0.5.0/). 
Refs:
- https://kuma.io/docs/0.5.0/policies/mutual-tls/
- https://kuma.io/docs/0.5.0/policies/traffic-metrics/

Fix the v0.5.0 docs

---

docs/.vuepress/theme/components/custom/Policies.vue

Disabled the upscaling on hover for the Policies page tiles because Chrome on Retina screens has a recurring issue with it. Random borders disappear after hover when paired with TailwindCSS grid columns. The only real fix right now is to disable the scaling that occurs on hover.

Policies page tile hover fix

---

bin/setup-redirects/index.js

This PR adds a wildcard `Access-Control-Allow-Origin` header for the `[latest_version](https://kuma.io/latest_version)` URL so that we can properly fetch the latest version string in things like front end apps where this is very strict.

Access-Control-Allow-Origin CORS header for latest version URL

---

docs/docs/0.5.1/documentation/dps-and-data-model.md
docs/docs/0.5.1/documentation/http-api.md

Change DP format to new outbound with tags. This is backwards compatible change - meaning you can still use `service: backend`

docs(*) dataplane outbound new format

---

docs/docs/0.6.0/policies/health-check.md

Cleaned up Health Check example:
```
The HealthCheck "proxy-to-random-sports-team" is invalid: 
* spec.conf.interval: must have a positive value
* spec.conf.timeout: must have a positive value
* spec.conf.unhealthyThreshold: must have a positive value
* spec.conf.healthyThreshold: must have a positive value
```
- removed double reference of kind
- fixed conf key in HealthCheck type

cleaned up Health Check examples

---

docs/docs/0.4.0/policies/traffic-log.md
docs/docs/0.5.0/policies/traffic-log.md
docs/docs/0.5.1/policies/traffic-log.md
docs/docs/0.6.0/policies/traffic-log.md

Fixes a broken link to the Envoy docs on command operators across several docs versions.

fix: Broken link to Envoy docs on command operators

---

docs/docs/0.7.1/documentation/deployments.md
docs/docs/0.7.1/documentation/dps-and-data-model.md
docs/docs/0.7.1/documentation/secrets.md

Just saw that some links pointing to an older version of the documentation (yellow banner) and fixed this quickly. Tested it locally with yarn docs:dev.

Fix typo and linking to older docu versions

---

docs/docs/0.7.2/installation/openshift.md

A couple of findings.
1) We don't actually need `anyuid`, we are not using root user. We need `nonroot`
2) It's less confusing to apply this on the namespace (when I started openshift for the first time I wasn't sure what to put in service account)
3) I think this should be a tip, not a warning. Warning sounds really negative in installation procedure
4) I added sample error what it looks like if you forget to do this. I was confused when I first started OpenShift and forget to do it
5) For Kuma Demo we actually need `anyuid` because of postgres

OpenShift improvements

---

docs/.vuepress/theme/styles/custom/base/_structure.scss

I'm lowering the padding in `code` blocks which looks more elegant end
is easier to read (I think) when you have two or more code block on top
of each other as before it was looking as one, solid block and it was
hard to differenciate the items between each other.
Before:
After:

style(docs) smaller padding in code blocks

---

docs/docs/1.0.3/documentation/http-api.md
docs/docs/1.0.3/policies/health-check.md

Modified API documentation by adding additional configuration block
(http) to HealthChecks and also modified HealthCheck Policy
documentation but introducing additional example for policy configured
to use HTTP protocol for health checks

FOR NEXT docs(*) http health checks

---

docs/.vuepress/theme/components/custom/Install.vue
docs/install/latest.md

This change adds the newsletter form to the bottom of the Install page.
**Note:**  When the form submits, it will redirect back to the Kuma homepage and display the success message there. This is a Pardot form handler limitation we've been facing since day one (SalesForce does not allow AJAX submissions at all on any of their form handlers).

Install page newsletter form

---

docs/.vuepress/theme/components/SidebarLinks.vue
docs/.vuepress/theme/layouts/Redirect.vue
netlify.toml

- 4096 MB of memory was not enough so I bumped it to 8192 MB
- Changed `created` lifecycle hooks to `mounted` as `created`
is unavailable in the SSR environment

fix(*) fix build

---

docs/docs/1.0.7/policies/traffic-metrics.md

The doc was still mentioning `http` when the api is `grpcs` now.
Fix: https://github.com/kumahq/kuma/issues/1515
Signed-off-by: Charly Molter <charly@koyeb.com>

Correct outdated doc on kuma-prometheus-sd

---

docs/_blog/2021-2-10-kuma-1-0-7.md
docs/_blog/2021-2-19-kuma-1-0-8.md

When writing blog posts, we can do this in the top frontmatter part of the markdown file:
```md
---
title: Kuma 1.0.7 Released with Jobs and Service-less Support
description: Kuma 1.0.7 Released with Jobs and Service-less Support
date: 2021-2-10
tags:
- Release
canonicalUrl: 'https://konghq.com/blog/kuma-1-0-7-released'
---
```
The tl;dr on canonical URLs from Google:
>A canonical URL is the URL of the page that Google thinks is most representative from a set of duplicate pages on your site.

Canonical links for all blog posts that were missing it

---

docs/policies.md

Pushed to kick off netlify build bc it appears that the `latest` value in a URL doesn't map to the actual latest docs directory in a local build :-(
All good on netlify: https://deploy-preview-403--kuma.netlify.app/docs/1.1.1/security/certificates/#data-plane-proxy-to-control-plane-communication

fix broken link

---

docs/docs/1.1.5/documentation/http-api.md
docs/docs/1.1.5/policies/health-check.md

- Updated HealthCheck policy docs - combined http and tcp
manifests in one, as with the last changes you can specify
both in one manifest, also added `reuseConnection` to examples
- Updated API reference

feat(*) docs for healthcheck changes

---

docs/docs/1.1.6/policies/circuit-breaker.md
docs/docs/1.1.6/policies/fault-injection.md
docs/docs/1.1.6/policies/health-check.md
docs/docs/1.1.6/policies/how-kuma-chooses-the-right-policy-to-apply.md
docs/docs/1.1.6/policies/proxy-template.md
docs/docs/1.1.6/policies/retry.md
docs/docs/1.1.6/policies/timeout.md
docs/docs/1.1.6/policies/traffic-log.md
docs/docs/1.1.6/policies/traffic-permissions.md
docs/docs/1.1.6/policies/traffic-route.md
docs/docs/1.1.6/policies/traffic-trace.md

Docs on matching were stale.
TrafficPermission is also matched by the most specific one, it was "aggregate" back in the early days.
I added a description of the types of policy (mirroring some concepts from the codebase).
I added a note to every policy which kind of policy it is so the user has more knowledge of how it matches and where it is applied.

rewrite policy matching

---

docs/docs/1.2.0/policies/general-notes-about-kuma-policies.md

This PR rewords and clarifies the warning regarding the use of arbitrary tags on `destinations` selectors for Kuma policies. It also fixes a typo in the same warning.

Reword warning on arbitrary tags in destination selectors

---

docs/docs/1.2.0/policies/timeout.md

This PR fixes an incorrect reference in the "Matching" section for the Timeout policy. This section incorrectly referenced the Retry policy.

Fix Timeout Matching section

---

docs/.vuepress/public/robots.txt

This fix removes old versions of Kong documentation from search
results. When users search for Kuma documenatation the top
result is frequently an old version of Kuma cached by the search
engine. This change, on the next crawl, will remove those.
Follows Google Robot Spec
https://developers.google.com/search/docs/advanced/robots/robots_txt

(docs) Add Disallow statements to robots.txt for old versions

---

docs/docs/1.2.2/policies/traffic-trace.md

Add instructions for exposing the APM port in a Kubernetes service for consumption by Kuma.

docs(kuma-cp) Add datadog APM service example.

---

docs/docs/1.2.3/installation/amazonlinux.md
docs/docs/1.2.3/installation/centos.md
docs/docs/1.2.3/installation/debian.md
docs/docs/1.2.3/installation/docker.md
docs/docs/1.2.3/installation/eks.md
docs/docs/1.2.3/installation/kubernetes.md
docs/docs/1.2.3/installation/macos.md
docs/docs/1.2.3/installation/openshift.md
docs/docs/1.2.3/installation/redhat.md
docs/docs/1.2.3/installation/ubuntu.md

The 1.2.3 docs were cut with a missing version number from the download
URLs. This change fixes the URLs but not the underlying problem that
caused the version to be absent.
This updates #492.
Signed-off-by: James Peach <james.peach@konghq.com>

fix(*) add missing 1.2.3 version to download links

---

docs/docs/1.2.3/documentation/http-api.md

Noticed that we are missing one field in api docs

fix(http-api) /dataplane+insights contain total field

---

docs/docs/1.2.3/policies/traffic-trace.md

Signed-off-by: Jennifer Rondeau <jennifer.rondeau@konghq.com>
Fixes #496 
VuePress does not like tips nested inside tabs (and I checked only the K8s tab for initial PR :-( )
PTAL @jpeach

fix misplaced tip section that broke tabs

---

docs/docs/1.2.3/policies/mutual-tls.md

this one will go to the next minor

docs(policies) intermediate CA

---

docs/docs/1.2.3/documentation/http-api.md

We were missing `version` field in `zones+insights` docs.
Also adjusted curl URL to be the correct one.

docs(http-api) adjust zones+insights fields

---

docs/docs/1.2.3/installation/docker.md
docs/docs/1.3.0/installation/amazonlinux.md
docs/docs/1.3.0/installation/centos.md
docs/docs/1.3.0/installation/debian.md
docs/docs/1.3.0/installation/docker.md
docs/docs/1.3.0/installation/eks.md
docs/docs/1.3.0/installation/kubernetes.md
docs/docs/1.3.0/installation/macos.md
docs/docs/1.3.0/installation/openshift.md
docs/docs/1.3.0/installation/redhat.md
docs/docs/1.3.0/installation/ubuntu.md

Looks like we forgot to replace version number in a bunch of install docs for 1.3.0, as well as docker install in 1.2.3.

docs(kuma-cp) Install instructions missing versions

---

docs/docs/4.4.4/documentation/http-api.md
docs/docs/4.4.4/other/compatibility.md

As MeshInsights will contain `dataplanesByTypes` field which will
contain aggregated by type statistics for dataplanes
Also updated supported version of Kubernetes as we are now
supporting k8s 1.17+

docs(*) update api reference for aggregate stats

---

docs/docs/1.1.0/policies/mutual-tls.md
docs/docs/1.1.1/policies/mutual-tls.md
docs/docs/1.1.2/policies/mutual-tls.md
docs/docs/1.1.3/policies/mutual-tls.md
docs/docs/1.1.4/policies/mutual-tls.md
docs/docs/1.1.5/policies/mutual-tls.md
docs/docs/1.1.6/policies/mutual-tls.md
docs/docs/1.2.0/policies/mutual-tls.md
docs/docs/1.2.1/policies/mutual-tls.md
docs/docs/1.2.2/policies/mutual-tls.md
docs/docs/1.2.3/policies/mutual-tls.md
docs/docs/1.3.0/policies/mutual-tls.md

we were using config instead of conf

Fix bad yaml in mTLS examples

---

docs/docs/4.4.4/networking/dns.md

Reword documentation to let people select virtual-outbound as favoured option

Add `serviceVipEnabled` configuration

---

docs/docs/1.4.0/documentation/http-api.md

We had wrong response for `Zones` in our docs. This PR set the current response.

docs(http-api) update zone field

---

docs/docs/1.4.0/quickstart/kubernetes.md
docs/docs/1.4.0/quickstart/universal.md
docs/docs/1.4.1/quickstart/kubernetes.md
docs/docs/1.4.1/quickstart/universal.md

- The demos were broken since we now have an allow-all-default traffic-permission.
Switched this steps to remove the policy, notice it is broken and add it back
- Universal was creating DPs that bind to 0.0.0.0 which causes admin listeners errors
<Explain you change!>
Did you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?

docs(quickstart): fix standalone demo and tp policies

---

docs/docs/dev/networking/dns-cp.md
docs/docs/dev/networking/dns.md
docs/docs/dev/networking/networking.md
docs/docs/dev/networking/service-discovery.md
docs/docs/dev/networking/transparent-proxying.md
docs/docs/dev/sidebar.json

* Assume across the networking docs that DNS in dp is the default
* Extract DNS in the CP to the separate doc with warning about deprecation
* Remove duplication of setup instructions between DNS and Transparent Proxying page
* Add reachable services

docs(networking) rewrite transparent proxy and dns

---

docs/docs/1.4.x/documentation/dps-and-data-model.md
docs/docs/1.4.x/documentation/fine-tuning.md
docs/docs/1.4.x/documentation/kubernetes-annotations.md
docs/docs/dev/documentation/dps-and-data-model.md
docs/docs/dev/documentation/fine-tuning.md
docs/docs/dev/documentation/kubernetes-annotations.md

Some labels/annotations can work either on namespace or pods.
This should be documented
Also correct 2 minor typos

fix(refDoc): ensure both namespace of pod options are documented

---

docs/docs/dev/documentation/http-api.md

Updated HTTP API reference with new `/tokens/dataplane` endpoint. In the code, it calls the same backend as the older `/tokens` endpoint, so I believe that ref is good.
Under `/tokens` path there is also `/zone` and `/zone-ingress`. I added them to the top level list, but they don't have an existing paragraph later in the doc. May need to collect more info on how those are used.

docs(kuma-cp): update tokens HTTP API endpoint

---

docs/docs/dev/policies/mesh.md

Added notes to the Mesh documentation to note that in k8s mode Mesh object spans namespaces and draws from all namespaces to consume policies.
I thought this was the most logical place to put this information. If there is anywhere else it needs to go, I can update.

docs(kuma-cp): clarify mesh and namespace relationship

---

docs/docs/1.4.x/documentation/kubernetes-annotations.md
docs/docs/dev/documentation/kubernetes-annotations.md

`kuma.io/mesh` only works as an annotation, bug from https://github.com/kumahq/kuma-website/pull/678

fix(kubernetes-annotations): kuma.io/mesh is an annotation not a label

---

docs/docs/1.5.x/documentation/gateway.md
docs/docs/dev/documentation/gateway.md

This was hiding the info for GatewayRoute

fix(gateway): fix badly closed tab

---

docs/docs/1.5.x/quickstart/kubernetes.md
docs/docs/dev/quickstart/kubernetes.md

Based on the instruction, I wasn't able to remove `TrafficPermissions`on K8s because it had `-` in between the words. It works for `kumactl` but for `kubectl` it isn't the correct value.

Changed traffic-permission to trafficpermission typo for kubectl

---

docs/.vuepress/theme/components/custom/Community.vue
docs/.vuepress/theme/global-components/CommunityCallForm.vue
docs/.vuepress/theme/store/index.js
docs/community/README.md

We publish recordings of the Kuma Community Calls, but we don't have a link publicly available. This PR adds the link to the playlist on website:

docs(*): add link to the YT playlist

---

docs/docs/1.5.x/policies/protocol-support-in-kuma.md
docs/docs/dev/policies/protocol-support-in-kuma.md

A long time ago @tharun208 introduced support of configuring protocol using `appProtocol` field in Kubernetes instead of this awkward annotation.
He added docs https://github.com/kumahq/kuma-website/pull/369 but it was lost for some reason.
We now support Kubernetes 1.19+ so this should be a default way of configuring the protocol with the old way still available for backward compatibility.

docs(policies): appProtocol support by default

---

.github/workflows/sync-generated.yml
sync_generated.sh

We were not doing a deep checkout of Kuma which resulted in the job
not checking out new branches

fix: improve doc gen to work with branches

---

docs/docs/1.5.x/documentation/dps-and-data-model.md
docs/docs/dev/documentation/dps-and-data-model.md

It makes sense to tell users about dp tokens in dp universal doc.
Also add kubectl example to see the dataplane for a pod.
Fix #594

fix(dp): add link to dp-token from the dataplane doc

---

docs/docs/1.4.x/security/api-server-auth.md
docs/docs/1.5.x/security/api-server-auth.md
docs/docs/dev/security/api-server-auth.md

We did not removed this in Kuma 1.5.0. We should not put in docs when something will be removed, because plans change and sometimes we postpone removal.

docs(security): delete remove admin cert in 1.5.x

---

docs/docs/dev/documentation/kubernetes-annotations.md

Adds documentation for the `kuma.io/service-account-token-volume` annotation in Kubernetes mode.

docs(documentation): add sa-token volume annotation

---

docs/docs/dev/policies/external-services.md

Added possibility to route traffic to external services in multizone setup.
When localityawareloadbalancing is enabled and zoneegress, and external service
label kuma.io/zone: xxx traffic to the external service will be routed through
the zone where the external service belongs to.
The feature works when routing.localityawareloadbalancing and routing.zoneEgress enabled and
ExternalService needs to have a tag kuma.io/zone.
https://github.com/kumahq/kuma/issues/3901 and https://github.com/kumahq/kuma/pull/4048

feat(docs): added description of locality lb with zone egress

---

docs/docs/1.6.x/installation/helm.md
docs/docs/dev/installation/helm.md

This PR modifies the Helm installation instructions to note that at least version 3.8.0 is required to use the Helm charts. This change was made only for the 1.6.x version of the documentation.
Yes
Yes

Add minimum Helm version to documentation

---

docs/.vuepress/public/installer.sh

See https://github.com/kumahq/kuma/issues/3814 and https://github.com/kumahq/kuma/pull/4167.
This will only attempt the download if the version is at least `1.7.0`, which is the first release when the above PRs will run.

feat(installer.sh): download kumactl if the Linux distribution doesn't have an archive

---

docs/.vuepress/config.js

Link defined [here](https://github.com/kumahq/kuma-gui/blob/084e76632d92c19b29507fa56da96ae70b53c80e/src/views/Entities/components/MultizoneInfo.vue#L18) results in a 404 because the page was moved. This fixes it.

fix: add redirect for deployments docs that returned 404 in gui

---

docs/.vuepress/public/installer.sh
docs/.vuepress/theme/components/Navbar.vue
docs/.vuepress/theme/global-components/Footer.vue
docs/docs/1.6.x/installation/redhat.md
package.json
tests/test-installer.sh

Installer on debian fails with:
```
sh: 21 Bad substitution
sh: 94: Syntax error: redirection unexpected
```
because it uses `bash` specific things when the shell is defined as `sh`. This PR fixes it and also adds a short test file to check if the installer succeeds on the distributions we list in "install" section in the sidebar. 
I also found that:
- in the sidebar "Redhat" was wrongly named "Debian" so I fixed that as well.
- we use an old name for this project in some places - and now that "[konvoy](https://d2iq.com/products/konvoy)" is actually a product we should not use that name 
Have you read …

fix: installer script on debian

---

docs/docs/dev/explore/gateway.md

I think we might want to separate builtin & delegated gateway docs at some point.
[Rendered](https://deploy-preview-831--kuma.netlify.app/docs/dev/explore/gateway/#cross-mesh)

docs(gateway): add cross-mesh docs

---

docs/.vuepress/public/installer.sh

Improve the shell scripts according to shellcheck + allow vars
like `PRODUCT_NAME`, `LATEST_VERSION` or `REPO_PREFIX` to be
provided in advance.
Set fallback for `$ARCH` variable value to `amd64`

refactor: adjust installer.sh to possible reuse

---

docs/docs/1.1.x/policies/retry.md
docs/docs/1.2.x/policies/retry.md
docs/docs/1.3.x/policies/retry.md
docs/docs/1.4.x/policies/retry.md
docs/docs/1.5.x/policies/retry.md
docs/docs/1.6.x/policies/retry.md
docs/docs/1.7.x/policies/retry.md
docs/docs/dev/policies/retry.md

fix: use `maxInterval` instead of `maxDuration` in Retry

---

docs/.vuepress/theme/components/Sidebar.vue
docs/.vuepress/theme/global-components/VersionNav.vue

Before when we changed the version during the dropdown the search
would happen on the previous version.
This is done as a hack in Vue but couldn't find another way ;)
Fix #855

fix(search): update the search index when changing version

---

backport.sh
docs/docs/1.7.x/explore/observability.md
docs/docs/dev/explore/observability.md

The landing page for observability should make it clear these things need to be enabled first.

docs(explore/observability): avoid users forgetting to configure observability

---

docs/docs/1.7.x/reference/kubernetes-annotations.md
docs/docs/dev/reference/kubernetes-annotations.md

There's a typo in the documentation that says the annotation is containes-patches, instead of container-patches.
✅ 
✅

Fix container-patches typo in annotation documentation

---

docs/docs/1.5.x/networking/transparent-proxying.md
docs/docs/1.6.x/networking/transparent-proxying.md
docs/docs/1.7.x/networking/transparent-proxying.md
docs/docs/dev/networking/transparent-proxying.md

Make sure folks don't miss running the dp with kuma-dp user

chore: add warning around transparent-proxy in universal

---

sync_generated.sh

Otherwise we can get errors with multiple branches:
```
fatal: 'release-1.1' matched multiple (2) remote tracking branches
```

fix(sync_generated.sh): add proper remote handling

---

.github/workflows/sync-generated.yml

As discussed here:
https://github.com/orgs/community/discussions/24664#discussioncomment-3244950
The user id we can get from looking at the `user` for the PRs created by
this app.
For example:
```
$ gh api repos/kumahq/kuma-website/pulls/923
```

fix(.github): use github app commit info

---

docs/.vuepress/theme/styles/vuepress-core/sidebar-group.scss

Fixes height, font size and opacity:
Before:
After:

fix(theme): fix display of sub items with sub items

---

docs/docs/dev/networking/cni.md

Added information that namespace needs to have a label or annotation `kuma.io/sidecar-injection` when using kuma cni.

docs(*): added information about NetworkAttachment and Kuma CNI

---

docs/docs/1.6.x/reference/http-api.md
docs/docs/1.7.x/reference/http-api.md
docs/docs/dev/reference/http-api.md

Joe Dascole pointed out that TrafficRoute REST API example was incorrect because it erroneously used `service` in place of `kuma.io/service`. 
Several other examples had the same problem. Dataplane related examples also incorrectly left out the `tags` layer. I tested a random sampling of all these changes before and after, and every one tested required this change.

docs(kuma-cp) fix tags which are missing "kuma.io/"

---

docs/.vuepress/config.js

Adds redirects for most available policy types (e.g. from `/docs/:version/policies/circuit-breakers/` to `/docs/:version/policies/circuit-breaker/`). This allows dynamically generating docs URLs to these policies (which mostly use singular forms) based on their API paths (which use plural forms).
See https://github.com/kumahq/kuma-gui/issues/341.

feat: adds redirects for policy URLs

---

docs/docs/dev/policies/traffic-log.md

We recently added support for all accesslog command operators defined by envoy. Updated docs to reflect this.

docs(kuma-cp): Update access log docs with full support

---

docs/docs/dev/quickstart/kubernetes.md

fix absolute path that would lead to new versions linking to old versions of the docs

docs(gateway): fix absolute path

---

docs/.vuepress/config.js

Adds the `Access-Control-Allow-Method` and `Access-Control-Allow-Headers` headers to the `/latest_version` URL path so that preflight requests include them and CORS requests with a set `Content-Type` are allowed.

fix: access control headers missing allowed method and headers

---

docs/.vuepress/theme/styles/custom/base/_type-and-content.scss

Fixes an issue with vertical scrollbars appearing on code blocks.
**After**:

fix: vertical scrollbars on code blocks

---

docs/_blog/2021-12-16-kuma-1-4-1.md

Kuma 1.4.1 blogpost was removed from konghq blog so this PR fixes the link checker by removing the link.

fix(build): fix link to kuma 1.4.1

---

docs/.vuepress/config.js

Disable limit chunk count plugin in dev to speed up rebuild times.
First build still takes a lot of time but subsequent rebuilds are much faster now:
previously:
```
success [10:38:00] Build 878092 finished in 28634 ms! ( http://localhost:8080/ )
```
now:
```
success [10:53:50] Build 07ff8b finished in 1461 ms! ( http://localhost:8080/ )
```
I've figured it out by recording a flamegraph and seeing that we spend a lot of time there:
If you want original flamegraph or instructions on how to do this let me know. …

fix(build): disable limit chunk count plugin in dev

---

CONTRIBUTING.md

Adds commit signing section to the contributing document.
Updates the contributing document based on the one found in Kuma.

docs: adds signing section to contributing doc

---

docs/docs/dev/explore/gateway-api.md

This adds a note about `GatewayClass` being created and `GatewayClass` example in another tab. Make sense? 
[rendered](https://deploy-preview-997--kuma.netlify.app/docs/dev/explore/gateway-api/#usage)
~Waiting on https://github.com/kumahq/kuma/pull/5001~

docs(gatewayapi): add note about auto `GatewayClass`

---

docs/docs/dev/explore/observability.md
docs/docs/dev/generated/resources/other_mesh.md
docs/docs/dev/policies/traffic-trace.md

This is updated docs for Datadog tracing split service functionality

docs(tracing) added documentation for datadog service split

---

docs/docs/1.2.x/policies/traffic-trace.md
docs/docs/1.3.x/policies/traffic-trace.md
docs/docs/1.4.x/policies/traffic-trace.md
docs/docs/1.5.x/policies/traffic-trace.md
docs/docs/1.6.x/policies/traffic-trace.md
docs/docs/1.7.x/explore/observability.md
docs/docs/1.8.x/explore/observability.md
docs/docs/dev/explore/observability.md

change the default label of datadog to match the one that is present when installing the agent

docs(kumacp): change the default label of datadog 

---

docs/docs/1.8.x/explore/gateway-api.md
docs/docs/dev/explore/gateway-api.md

Fixes a broken URL to the k8s docs which breaks the link checker because their redirection is implemented on the client side via JavaScript.

chore: fixes broken URL to k8s docs

---

docs/.vuepress/_snippets/install_os.md

vuepress adds a `v:pre` tag to a fenced code block, which escapes any vue interpolation and shows the plain, unprocessed code. This interferes with instances where you need the vue interpolation for the example code to make sense. I updated an escaped code block to use the same style as a block earlier in the snippet so its interpolation could work.
see https://github.com/vuejs/vuepress/issues/413
Signed-off-by: zachmandeville <webmaster@coolguy.website>

Use div for code block so vue interpolation works

---

docs/docs/1.3.x/documentation/configuration.md
docs/docs/1.4.x/documentation/configuration.md
docs/docs/1.5.x/documentation/configuration.md
docs/docs/1.6.x/documentation/configuration.md
docs/docs/1.7.x/documentation/configuration.md
docs/docs/1.8.x/documentation/configuration.md
docs/docs/dev/documentation/configuration.md

fix: kubectl being misspelled as kubactl in a few places

---

app/_headers
app/_plugins/generators/alias.rb
app/_plugins/hooks/latest_version.rb

Re-adds the missing `/latest_version` endpoint after the replatform to Jekyll. This file is used by the installer + GUI
Have you read [Contributing guidelines] Yes

Re-add the /latest_version endpoint

---

Makefile
WRITING-DOCUMENTATION.md

`make install` is broken because of the spaces.
I also updated `WRITING-DOCUMENTATION.md` because it was not obvious to me that I need to install the proper ruby version.

chore: fix makefile and update writing docs

---

app/_includes/sidebar.html
app/_layouts/default.html

The sidebar menu was not being rendered on non-docs pages for mobile devices.

Fix sidebar menu on mobile devices

---

app/_plugins/hooks/releases_json.rb

`/releases.json` was missing on the replatform. This commit re-adds the data

Generate /releases.json

---

app/_headers

CORS headers were missing, which means the GUI can't load the file

Add CORS headers to /latest_version and /versions.json

---

app/_data/versions.yml
app/_plugins/generators/redirects.rb
app/_plugins/generators/sitemap.rb
app/_plugins/generators/versions.rb
app/_plugins/hooks/latest_version.rb

The `latest: true` flag was used to soft launch new versions without triggering docs reindexing/GUI updates. This was removed in the replatform, and is now re-added.

Re-add the latest: true flag in versions.yml

---

app/_data/docs_nav_kuma_1.6.x.yml
app/_data/docs_nav_kuma_1.7.x.yml
app/_data/docs_nav_kuma_1.8.x.yml
app/_data/docs_nav_kuma_dev.yml
app/docs/dev/generated/cmd/kumactl/kumactl_generate_zone-ingress-token.md
app/docs/dev/generated/cmd/kumactl/kumactl_get.md
app/docs/dev/generated/cmd/kumactl/kumactl_get_meshaccesslog.md
app/docs/dev/generated/cmd/kumactl/kumactl_get_meshaccesslogs.md
app/docs/dev/generated/cmd/kumactl/kumactl_get_meshtrace.md
app/docs/dev/generated/cmd/kumactl/kumactl_get_meshtraces.md
app/docs/dev/generated/cmd/kumactl/kumactl_inspect.md
app/docs/dev/generated/cmd/kumactl/kumactl_inspect_meshaccesslog.md
app/docs/dev/generated/cmd/kumactl/kumactl_inspect_meshtrace.md
app/docs/dev/generated/cmd/kumactl/kumactl_uninstall.md
app/docs/dev/generated/cmd/kumactl/kumactl_uninstall_ebpf.md
app/docs/dev/generated/cmd/kumactl/kumactl_uninstall_transparent-proxy.md
app/docs/dev/generated/resources/other_mesh.md
app/docs/dev/generated/resources/policy_external-service.md
app/docs/dev/generated/resources/proxy_dataplane.md
sync_generated.sh

- Add back kuma-cp reference to the sidebar
- fix sync_generated.sh to transform markdown in jekyll compatible content

fix(generated): fix generated docs script

---

app/_includes/snippets/install_kumactl.md

Remove {% raw %} block surrounding code snippet that prevented the page version from being rendered
Fixes https://github.com/kumahq/kuma-website/issues/1064 
See https://deploy-preview-1096--kuma.netlify.app/docs/1.8.x/installation/kubernetes/

Fix variable interpolation in code snippet

---

app/docs/1.4.x/policies/fault-injection.md
app/docs/1.4.x/policies/health-check.md
app/docs/1.4.x/policies/rate-limit.md
app/docs/1.4.x/policies/traffic-route.md
app/docs/1.5.x/policies/circuit-breaker.md
app/docs/1.5.x/policies/fault-injection.md
app/docs/1.5.x/policies/health-check.md
app/docs/1.5.x/policies/rate-limit.md
app/docs/1.5.x/policies/traffic-route.md
app/docs/1.6.x/policies/circuit-breaker.md
app/docs/1.6.x/policies/fault-injection.md
app/docs/1.6.x/policies/health-check.md
app/docs/1.6.x/policies/mesh-trace.md
app/docs/1.6.x/policies/rate-limit.md
app/docs/1.6.x/policies/retry.md
app/docs/1.6.x/policies/traffic-route.md
app/docs/1.7.x/policies/circuit-breaker.md
app/docs/1.8.x/policies/retry.md
app/docs/dev/policies/retry.md
app/docs/dev/policies/timeout.md

Fix the syntax for tooltips/warnings. After the merge of the move to Jekyll, some files kept the old syntax and some got duplicated tooltips

Fix {% tip %} syntax after merge

---

app/docs/1.8.x/policies/retry.md
app/docs/dev/policies/retry.md

Closes https://github.com/kumahq/kuma-website/issues/1103
A client tried to apply `gateway-error` instead of `gateway_error` and that caused an error.

fix(kumacp): fix default retry on in retry policy

---

app/_plugins/filters/indent_filter.rb
app/docs/1.1.x/policies/retry.md
app/docs/1.2.x/policies/retry.md
app/docs/1.3.x/policies/retry.md
app/docs/1.4.x/policies/retry.md
app/docs/1.5.x/policies/retry.md
app/docs/1.6.x/policies/retry.md
app/docs/1.7.x/policies/retry.md
app/docs/1.8.x/policies/retry.md
app/docs/dev/policies/retry.md

It prepends 4 spaces to every line
It also fixes an edge case regarding code snippets being part of the
content to be indented. Previously, it was adding an extra newline to
the code snippet.
Fixes https://github.com/kumahq/kuma-website/issues/1102

Fix indentation filter

---

app/docs/1.7.x/explore/observability.md
app/docs/1.8.x/explore/observability.md
app/docs/dev/explore/observability.md

Add information that in order to see dataplane metrics, you first need to create Traffic Metrics policy.
Fixes: #1002 

docs(observability)  Add information that in order to see dataplane metrics, you first need to create Traffic Metrics policy

---

app/docs/1.1.x/installation/docker.md
app/docs/1.2.x/installation/docker.md
app/docs/1.2.x/quickstart/universal.md
app/docs/1.3.x/installation/docker.md
app/docs/1.3.x/quickstart/universal.md
app/docs/1.4.x/installation/docker.md
app/docs/1.4.x/quickstart/universal.md
app/docs/1.5.x/installation/docker.md
app/docs/1.5.x/quickstart/universal.md
app/docs/1.6.x/installation/docker.md
app/docs/1.6.x/quickstart/universal.md
app/docs/1.7.x/installation/docker.md
app/docs/1.7.x/quickstart/universal.md
app/docs/1.8.x/installation/docker.md
app/docs/1.8.x/quickstart/universal.md

Forgot to backport https://github.com/kumahq/kuma-website/pull/1125 in the orignal PR 🤦‍♂️.

feat(kumacp): backport docker auth to older versions of doc

---

app/docs/1.5.x/deployments/multi-zone.md
app/docs/1.6.x/deployments/multi-zone.md
app/docs/1.7.x/deployments/multi-zone.md
app/docs/1.8.x/deployments/multi-zone.md
app/docs/dev/deployments/multi-zone.md

Add info where to get ca when ingress deployed not alongside zone cp.
Closes https://github.com/kumahq/kuma-website/issues/913
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits) yes 

fix(kumadp): add missing info on multizone installation

---

Makefile

Re-generates the corresponding pages when the source content changes.
Fixes https://github.com/kumahq/kuma-website/issues/1128

Update `make run` to use jekyll serve instead of build

---

app/docs/dev/security/secrets.md

Signed-off-by: angel <angel.guarisma@konghq.com>
Removed the tip, the information was stronger without a tip but it was also breaking the formatting on the mesh website. 

formatting

---

app/docs/2.0.x/policies/meshtrace.md
app/docs/dev/policies/meshtrace.md

When Kuma got rid of protobuf for the new policies, we use pointers to express field optionality instead of the type wrappers.

docs: MeshTrace optional fields without 'value'

---

Gemfile
Gemfile.lock
Makefile
Procfile
bin/jekyll-vite
netlify.toml

Contributors can now run just one command locally `make run` locally, and it will take care of setting everything up for them.
It spins up:
* the `vite` server for the assets
* `Jekyll serve`
* `netlify dev` so that they can test the site locally with all the redirects in place. The `50s` sleep before running `netlify` is to allow `Jekyll` to build the site first, because it needs to generate the `_redirect` that is required by `netlify`.
It also fixes an issue with vite generating a `development` build in `production` due to a bad config.
cc @mheap 

Improve dev experience

---

app/docs/2.0.x/policies/introduction.md
app/docs/dev/policies/introduction.md

Add link to MeshTrafficPermission.

fix: add link to mesh traffic permission

---

app/_includes/version_alert.html
app/_includes/version_selector.html
app/_plugins/generators/redirects.rb

Related https://github.com/kumahq/kuma-website/issues/857
Make the `Go here` link point to the newest version of the page instead of the docs' index page

Link to newest version of the page in the version alert banner

---

app/docs/2.0.x/networking/transparent-proxying.md
app/docs/dev/networking/transparent-proxying.md
jekyll.yml

Fixed value of `--set` flag for installing control plane with ebpf as it was always prefixed with `kuma.` which was wrong.

fix(docs): fix ebpf install docs

---

app/docs/2.0.x/policies/meshaccesslog.md
app/docs/dev/policies/meshaccesslog.md

We were using MeshService with tags. Replaced with MeshServiceSubset

fix(meshaccesslog): subset bad example

---

app/_includes/snippets/install_kumactl.md

The command
```text
ln -s kuma-2.0.0/bin/kumactl /usr/local/bin/kumactl
```
was not working. Adding the current path - using the $PWD environment variable - make it work:
```text
ln -s $PWD/kuma-2.0.0/bin/kumactl /usr/local/bin/kumactl
```

Symbolic link to `kumactl` does not contain the full path

---

app/docs/1.4.x/deployments/multi-zone.md
app/docs/1.5.x/deployments/multi-zone.md
app/docs/1.6.x/deployments/multi-zone.md
app/docs/1.7.x/deployments/multi-zone.md
app/docs/1.8.x/deployments/multi-zone.md
app/docs/1.8.x/documentation/configuration.md
app/docs/2.0.x/deployments/multi-zone.md
app/docs/2.0.x/documentation/configuration.md
app/docs/dev/deployments/multi-zone.md
app/docs/dev/documentation/configuration.md
jekyll-dev.yml
jekyll.yml

[Related](https://github.com/Kong/docs.konghq.com/issues/4960) issue in Kong 's docs.
Helm commands were referencing  `kuma` instead of `kong-mesh` on kong docs,  because the value was hardcoded and we didn't handle it in any way.
This PR adds placeholders for `kuma` and `kuma/kuma` in helm commands, which we can replace in Kong's docs in Jekyll's configuration file.
This change doesn't affect Kuma's website, everything should look the same, but once we merge this, add the placeholder to `docs.konghq` and update the submodule, it will replace the placeholders with `kong-mesh` and `kong-mesh/kong-mesh`

Parameterize helm commands

---

app/_assets/javascripts/form.js

Pardot issues an http request to a specified url in their config once the ajax call is submited, in this case it is
https://kuma.io/community?form_success=true
Before migrating to Jekyll, we just ignored that callback and rendered a success message, even in the unlikely case that it could fail. After migrating to Jekyll, we added a success and error callbacks to handle both scenarios. However, the error handler gets executed in both scenarios, this is because the response the Ajax gets is a redirect and a parseError and there is no way to know whether the call was a success or not.
We are opting here to ignore the error case as before and just show the success message.
Did you sign your commit? …

Fix community form submission

---

app/_src/policies/meshhealthcheck.md

The format of header modifiers has changed in https://github.com/kumahq/kuma/pull/5757. This PR updates the doc for MeshHealthCheck

docs: update headers modifier format in MeshHealthCheck

---

app/_plugins/tags/tabs/tabs.rb

When creating a tabs group, we check whether there is one already with the same name within a page. Unfortunately, we were using checking whether it existed within a file and not the whole page. After a file was read, the tabs were cached, causing it to raise an error if the file was used again, e.g. when including a file in several docs. This was causing the check to raise.
The fix consists of checking whether the tab group exists on the page instead of within a file.

Fix tabs generation in single sourced pages

---

app/_common_redirects
app/_plugins/generators/redirects.rb
app/_redirects

Move most of the redirects to files so we can re-use them in kong-mesh, instead of having a list of hardcoded urls.

Move redirects to files so we can reuse them in kong-mesh

---

app/_common_redirects
app/_posts/2023-02-01-kuma-2-1-0.md
app/_redirects
app/_src/reference/http-api.md
app/docs/1.6.x/reference/http-api.md
app/docs/1.7.x/reference/http-api.md
app/docs/1.8.x/reference/http-api.md
app/docs/2.0.x/reference/http-api.md

Using 301 was causing browsers to cache the redirect which was causing problems when the latest version changed

fix: use 302 redirects for latest and pagination doc

---

app/_common_redirects
app/_redirects

Remove a malformed redirect and move `/docs/latest/* /docs/LATEST_RELEASE/:splat 302` from `_common_redirects` to `_redirects`. We use `/latest/` in konghq for our docs.
**Note**:
There are a few redirects that are only valid for a few versions that we definitely want to fix, e.g.:
* `/docs/:version/other/ /docs/:version/other/enterprise 301` is only valid for versions 1.1.x to 1.5.x, should it redirect to `/introduction/enterprise` for newer versions?
* `/docs/:version/api/ /docs/:version/documentation/http-api 301`  ` is only valid for versions 1.1.x to 1.5.x, it should redirect to `/reference/http-api` for newer versions
Have you read [Contributing …

Fix common redirects

---

app/_data/docs_nav_kuma_dev.yml
app/_redirects
app/_src/deployments/stand-alone.md
app/_src/explore/gateway.md
app/_src/networking/cni.md
app/_src/production/install-kumactl.md
app/_src/production/use-kuma.md
app/_src/quickstart/kubernetes.md
app/_src/quickstart/universal.md

- Created a new page that will replace (at least parts) of the existing pages in the "Install" section. 
- Also, realized I should probably create a "Use Kuma" page as well to cover the remaining content from the install files, so I did that.
- Made redirects for the install files to point to the new "Install kumactl" page.
- Added the new pages to the dev nav file.
- Jira ticket: [DOCU-2859](https://konghq.atlassian.net/browse/DOCU-2859)
Did you sign your commit? Yes [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits)
❗ Question for reviewers: Should this topic be Kuma-only or should we bring it over to Mesh? The install instructions for Mesh …

(docs) Add the new "Install kumactl" page

---

app/_src/policies/meshaccesslog.md
app/_src/policies/meshtrace.md
app/docs/2.0.x/policies/meshaccesslog.md

closes https://github.com/kumahq/kuma-website/issues/1284
Rendered:
- MeshAccessLog [1](https://deploy-preview-1288--kuma.netlify.app/docs/dev/policies/meshaccesslog/#opentelemetry), [2](https://deploy-preview-1288--kuma.netlify.app/docs/dev/policies/meshaccesslog/#logging-to-multiple-backends)
- MeshTrace [1](https://deploy-preview-1288--kuma.netlify.app/docs/dev/policies/meshtrace/#opentelemetry), [2](https://deploy-preview-1288--kuma.netlify.app/docs/dev/policies/meshtrace/#opentelemetry-1)

feat(observability): document OTel for MeshTrace and MeshAccessLog

---

app/_src/policies/external-services.md

Added information on limitations in `ExternalServices` when `ZonEgress` is enabled.
fix: #1272

docs(external-service): added limitations of working external services with Lb and egress

---

app/_src/production/cp-deployment/multi-zone.md

otherwise crds are installed and we don't want that

fix(deployment): add skip crds in universal on k8s instructions

---

app/installer.sh

Add `--print-version`. Useful, for example, when using `VERSION=preview`

feat(installer.sh): add ability to only print version

---

app/_src/explore/inspect-api.md

docs(inspect): use --type=config=dump

---

app/_src/policies/meshcircuitbreaker.md
app/_src/policies/meshhealthcheck.md
app/_src/policies/meshhttproute.md
app/_src/policies/meshloadbalancingstrategy.md
app/_src/policies/meshratelimit.md
app/_src/policies/meshretry.md
app/_src/policies/meshtimeout.md
app/_src/policies/meshtrace.md

It's not supported by `MeshTrace` or any other policy. Closes https://github.com/kumahq/kuma/issues/6497

docs: remove references to MeshGatewayRoute as targetRef kind

---

.github/workflows/ci.yml

`.length` doesn't exist, I'm not sure how or if this ever worked...
See https://github.com/kumahq/kuma-website/pull/1237/files#diff-6b06584addad16d3c7ef039f811a4f13b75edd1fc4785b239e55420291fbb149

ci(.github): fix vale check

---

.github/styles/Vocab/Base/accept.txt
app/_data/docs_nav_kuma_dev.yml
app/_src/explore/gateway-api.md

Eventually I'd like to link to a blog post/avoid summarizing GEP again here.
[rendered](https://deploy-preview-1352--kuma.netlify.app/docs/dev/explore/gateway-api/#service-to-service-routing)

docs(GatewayAPI): add short GAMMA mention

---

app/_src/production/cp-deployment/systemd.md

Add missing spaces around "=" in systemd docs.

chore: add missing spaces around "=" in systemd docs

---

.github/styles/Vocab/Base/accept.txt

Add some missing words with `end` prefix (used in jekyll templating) to vale accepted vocabulary, to get rid of some of the false-positive warnings.

chore: add some "end*" wods to vale vocabulary

---

app/_common_redirects

Applies only to legacy policies as the new ones just work
Part of kumahq/kuma-gui#847

fix: add redirects from policynames to policy docs

---

app/_common_redirects
app/_data/docs_nav_kuma_2.2.x.yml
app/_data/docs_nav_kuma_2.3.x.yml
app/_data/docs_nav_kuma_dev.yml
app/_layouts/default.html
app/_redirects
app/_src/documentation/configuration.md
app/_src/production/cp-deployment/systemd.md
app/_src/production/dp-config/dpp-on-universal.md
app/_src/production/upgrades-tuning/upgrades.md
app/_src/reference/kubernetes-annotations.md
jekyll-dev.yml
jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/jsonschema.rb
jekyll.yml

We always should use the newest path and systemd conf shouldn't include too much env specific things

fix: always use reference/kuma-cp and fix systemd conf

---

app/_src/policies/meshretry.md

docs(MeshRetry): add info about targetRef MeshGateway

---

app/_src/explore/observability.md

Reformatting descriptions for the organization of multiple Prometheus instances in multi-zone environments.

Reformatting descriptions for the organization of multiple Prometheus instances in multi-zone environments

---

app/_data/docs_nav_kuma_2.4.x.yml
app/_data/docs_nav_kuma_dev.yml

The previous setup was causing docs.konghq.com to fail

fix(changelog): 2.4.x and dev set generate: false

---

app/_redirects
app/_src/production/dp-config/dpp-on-kubernetes.md
app/_src/reference/kubernetes-annotations.md

document waiting for sidecar to be ready before running other init containers
closes https://github.com/kumahq/kuma-website/issues/1448
xref https://github.com/kumahq/kuma/pull/7583

feat(lifecycle): document waiting for sidecar to be ready

---

.github/workflows/ci.yml

ubuntu 22.10 started failing https://github.com/kumahq/kuma-website/actions/runs/6169639158/job/16781025677?pr=1460#step:3:10 not sure if worth investigating 
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits) yes 

ci(installer): run tests on ubuntu 22.04

---

.github/styles/Vocab/Base/accept.txt

Add word `RFC` to allowed in vale dictionary

chore(vale): add word "RFC" to allowed in vale vocabulary

---

app/_src/networking/dns.md

Adding reference to DNS standards as per ([RFC1035](https://www.ietf.org/rfc/rfc1035.txt)).

docs(dns): mention DNS standards RFC in dns documentation

---

app/_common_redirects
app/_src/documentation/configuration.md
app/_src/production/cp-deployment/multi-zone.md
app/_src/production/cp-deployment/stand-alone.md
app/_src/production/deployment/multi-zone.md
app/_src/production/deployment/stand-alone.md
app/_src/production/dp-config/cni.md
app/_src/production/secure-deployment/certificates.md
jekyll-kuma-plugins/lib/jekyll/kuma-plugins.rb
jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/cpinstall.rb

We now redirect to install standalone instead of install kumactl.
Added a link to how to install in each mode from the topology page
Fix https://github.com/kumahq/kuma-website/issues/1458
Built on top of: #1447

add plugin to generate helm and kumactl install

---

app/_src/policies/meshtimeout.md
jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/cpinstall.rb
jekyll-kuma-plugins/spec/jekyll/kuma-plugins/liquid/tags/cpinstall_spec copy.rb

After introducing `cpinstall` plugin, `policy_yaml` plugin stopped working

fix: fix policy_yaml rendeing

---

app/_src/policies/meshproxypatch.md

Adjust docs of MeshProxyPatch policy to include support of MeshGateway targetRefs.

feat(policies): add support for MeshGateway in MeshProxyPatch

---

app/_src/explore/gateway.md

This was implemented a while back
fix #1453

fix(gateway): make xmesh gateway multizone limitation version specific

---

app/_src/policies/general-notes-about-kuma-policies.md
app/_src/production/deployment/stand-alone.md
app/docs/1.3.x/policies/general-notes-about-kuma-policies.md
app/docs/1.4.x/deployments/stand-alone.md
app/docs/1.4.x/policies/general-notes-about-kuma-policies.md
app/docs/1.5.x/deployments/stand-alone.md
app/docs/1.5.x/policies/general-notes-about-kuma-policies.md
app/docs/1.6.x/deployments/stand-alone.md
app/docs/1.6.x/policies/general-notes-about-kuma-policies.md
app/docs/1.7.x/deployments/stand-alone.md
app/docs/1.7.x/policies/general-notes-about-kuma-policies.md
app/docs/1.8.x/deployments/stand-alone.md
app/docs/1.8.x/policies/general-notes-about-kuma-policies.md
app/docs/2.0.x/deployments/stand-alone.md
app/docs/2.0.x/policies/general-notes-about-kuma-policies.md

There are a few minor typos on the Kuma website. 
This PR is to fix those I found when I was reading through the docs.
Yes.
Yes.

fix: typos in doc (proxies and slashes)

---

Makefile
app/_assets/styles/custom/components/_sidebar.scss
app/_assets/styles/vuepress-core/sidebar.scss
jekyll-dev.yml
jekyll.yml

Fixes the sidebar being too tall which messes up the scrolling behavior: one currently often needs to scroll all the way to the bottom of the page to see the bottom items of the sidebar. This PR changes the sidebar behavior so that the sidebar can always be scrolled individually regardless of the main content height.
Resolves #1321.
I made some development setup-related changes that I ran into while working on this.
One note on the development setup using `make run`: I had trouble getting things working and ultimately, with the help of @fabianrbz, got a working development server working by removing `netlify: sleep 50 && netlify dev` from the `Procfile`. I haven’t committed this change here because I’m not entirely sure what it implies.

fix: sidebar being too tall

---

app/_assets/styles/custom/config/_mixins.scss
app/_assets/styles/custom/config/_variables.scss

Addresses the Sass deprecation warnings one sees during the build/serve commands.

chore: address Sass deprecation warnings

---

app/_src/policies/meshcircuitbreaker.md

remove `name: default` on targetRef Mesh as it's invalid

fix: update meshcircuitbreaker.md

---

app/_data/docs_nav_kuma_2.5.x.yml
app/_data/docs_nav_kuma_dev.yml
app/_src/policies/meshaccesslog.md
app/_src/policies/meshcircuitbreaker.md
app/_src/policies/meshfaultinjection.md
app/_src/policies/meshhealthcheck.md
app/_src/policies/meshhttproute.md
app/_src/policies/meshloadbalancingstrategy.md
app/_src/policies/meshproxypatch.md
app/_src/policies/meshratelimit.md
app/_src/policies/meshretry.md
app/_src/policies/meshtcproute.md
app/_src/policies/meshtimeout.md
app/_src/policies/meshtrace.md
app/_src/policies/meshtrafficpermission.md

feat: make new policies not beta

---

app/_src/production/upgrades-tuning/fine-tuning.md

A couple of changes to auto reachable services docs:
* You don't need mTLS
* Let's not repeat how to configure CP every time, but link to configuration docs that explain how to do it.
* Fixed yaml example. `policy_yaml` expects universal
* The error was not 403 before, it was 503 because RBAC is L4. I checked this with demo
* Be more explicit about namespace

docs(perf): improve auto reachable services docs

---

app/_src/policies/targetref.md

The name has to be there for MeshService, MeshServiceSubset and MeshGatewayRoute

docs(policies): name has to be defined with a bunch of kinds

---

.github/styles/Vocab/Base/accept.txt
app/_src/production/dp-config/transparent-proxying.md

A bunch of improvements to docs to be able to actually run this on Ubuntu.
* How to replace `iptables` with supported version
* Drop `--skip-resolve-conf`, it says it's deprecated
* Add port `22` to exclude by default. Users will use this doc as a guide. I was locked out from the VM
* `iptables` are not preserved on the machine by default
* `uninstall` command does not exist. There is no point in referencing it until we get this done.
* Template of DPP was broken
* Added clarification that the service itself has to be run as any other user (a user was recently confused about this)
Additionally, I had problems with installation that I had to provide `--wait=0`. This should be fixed by https://github.com/kumahq/kuma/pull/8364
Fix #1528

docs(tproxy): improve tproxy instructions

---

jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/cpinstall.rb

There's a slight difference between Kuma and Kong Mesh regarding the base segment of the docs' URL.
For Kuma, all the docs live under `/docs/`. Unfortunately, that's not the case for Kong Mesh. Kong docs renders multiple products, so we namespace the docs with the corresponding product name, i.e. they live under `/mesh/`.
This commit updates the tag's code so that it uses the base path in which the page is generated as the first URL segment. That way we can re-use the code on both platforms.
It also modifies the rendered link, so that it uses `page.release` instead of `page.version` to work for both docs sites.
Visit [multi-zone deployments](https://docs.konghq.com/mesh/latest/production/cp-deployment/multi-zone/) and choose `helm`. The `follow these steps` link is broken.
Did you sign …

Fix cpinstall tag for kong-mesh

---

Gemfile.lock
app/_src/production/cp-deployment/kubernetes.md

Add a paragraph about the option required to run Kuma on GKE Autopilot.

add some info about the GKE autopilot support

---

app/_src/introduction/kuma-requirements.md

Per [Code](https://github.com/kumahq/kuma/blob/2.5.1/pkg/config/plugins/runtime/k8s/config.go#L54-L61) the default CPU limit for Sidecar Container is 1000m. 
This PR will correct the typo in the documentation.

docs(kuma-requirements): update sidecar container default cpu limit

---

app/_src/production/dp-config/transparent-proxying.md

- Fixes broken link in the transparent proxying docs
- Fixes few small spelling mistakes and typo
- Adds missing code block closing <code>```</code>
- Removes additional space before some of the code blocks in one of the lists

docs(transparent-proxy): fix broken link

---

app/_src/policies/virtual-outbound.md

It was confusing to users that we're not using a label that exists.

fix(virtualOutbound): use k8s.kuma.io/service-port in examples

---

app/_src/policies/meshmetric.md

Add missing spec otherwise the policy does not render correctly.
We might need to think about warning / erroring out on this.

fix(meshmetrics): add missing spec

---

app/_data/docs_nav_kuma_dev.yml
app/_src/documentation/configuration.md
app/_src/explore/gateway.md
app/_src/index.md
app/_src/installation/docker.md
app/_src/installation/helm.md
app/_src/installation/openshift.md
app/_src/quickstart/kubernetes-demo.md
app/docs/1.8.x/explore/gateway.md
app/docs/2.0.x/explore/gateway.md

Rewrite quickstart.
The goal is to have a very opinionated quickstart (kubernetes, helm, kind, mesh traffic permission). So we can then build guides (like federating zone) as a next step after you complete it.
Quickstart for Universal is intentionally gone. I'm not a big fan of this, but it's what we discussed. We want to reintroduce this after the release.

feat(quickstart): rewrite kubernetes quickstart

---

app/_src/explore/inspect-api.md

Update [Explore / Inspect API](https://kuma.io/docs/dev/explore/inspect-api/) page with new policies
* Show new policies instead of legacy ones in returned strings
Relates to: https://github.com/kumahq/kuma-website/issues/1599

docs(inspect-api): update page to show new policies

---

app/_data/docs_nav_kuma_dev.yml
app/_src/policies/protocol-support-in-kuma.md

This is to follow the information rearchitecture work. This for the moment use the existing pages as is and we can in the future do more complete rewrites.
Doesn't really do much to Gateway because it's done in its own separate PR

chore(sidebar): reorganize everything under `use kuma`

---

app/_src/networking/non-mesh-traffic.md

convert non-mesh traffic doc to use targetref policies since 2.6
xref: https://github.com/kumahq/kuma-website/issues/1599
2.5.0: https://deploy-preview-1615--kuma.netlify.app/docs/2.5.x/networking/non-mesh-traffic/#non-mesh-traffic
dev: https://deploy-preview-1615--kuma.netlify.app/docs/dev/networking/non-mesh-traffic/#non-mesh-traffic

docs(networking): convert non-mesh traffic doc to use targetref policies

---

app/_src/production/upgrades-tuning/fine-tuning.md

Since 2.6 autoreachable services don't require external services.

docs(auto-reachable): removed note about externalservices since 2.6

---

jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/jsonschema.rb

Kubebuilder 0.14 has introduced a change in how it handles new lines in field descriptions. Now, if there is a new line, it adds it to the object, causing rendering issues for the objects. I attempted to address this by utilizing the library option, but unfortunately, it is not supported (refer to https://github.com/showdownjs/showdown/issues/801).
As a workaround, I implemented a function that iterates over the object and removes new lines from the description field.
https://kuma.io/docs/2.6.x/policies/meshgatewayinstance/#schema
https://deploy-preview-1632--kuma.netlify.app/docs/2.6.x/policies/meshgatewayinstance/#schema

fix(jsonschema): remove new lines from description

---

app/installer.sh

When running a command:
```
curl https://kuma.io/installer.sh | VERSION=0.0.0-preview.v97af5da5e sh -
```
it attempts to use the URL (and fails):
```
https://packages.konghq.com/public/kuma-binaries-preview/raw/names/kuma-darwin-arm64/versions/0.0.0-preview.v97af5da5e/kuma-0.0.0-preview.v97af5da5e-darwin-arm64.tar.gz
```
the correct URL is (difference after the `/versions/`):
```
https://packages.konghq.com/public/kuma-binaries-preview/raw/names/kuma-darwin-arm64/versions/97af5da5e/kuma-0.0.0-preview.v97af5da5e-darwin-arm64.tar.gz
```

fix(installer): set VERSION to commit hash for previews

---

.github/workflows/ci.yml
app/installer.sh

continuing the work of @lobkovilya in https://github.com/kumahq/kuma-website/pull/1642 

ci(installer): add tests for various modes of installer

---

app/_src/explore/observability.md

Added info about MADS issue introduced in version 2.6.0 and how to fix it with Prometheus config

fix(policies): add warning for MADS long polling issue

---

app/_src/production/use-mesh.md

Clarify that admission server on 5443 is exposed on 443

docs(production): clarify port number in kube service

---

Gemfile.lock

Clean up the [platforms](https://bundler.io/v2.5/man/gemfile.5.html#PLATFORMS) section of the Gemfile.lock
We don't need to specify specific platforms, we can just list `ruby` and let bundler figure out if it needs to install platform-specific versions of the gems.

Fix rack dep

---

.github/workflows/ci.yml
app/installer.sh

Before we were using some graphQL black magic.
Now we use `gh run list` which enables to very strictly filter on successful workflow run
This should avoid failures in CI due to build-test-distribute waiting to be run

fix(installer.sh): make VERSION=preview more reliable

---

.github/workflows/ci.yml

exclude anchors for all github links since they are not server side rendered
continuation of https://github.com/kumahq/kuma-website/pull/1697 but for all GH links

chore(links): exclude anchors for all github links

---

app/_data/docs_nav_kuma_2.6.x.yml
app/_data/docs_nav_kuma_dev.yml
app/_src/production/upgrades-tuning/upgrade-notes.md

feat(upgrade): embed upgrade.md in docs

---

app/_src/quickstart/universal.md
app/docs/1.2.x/quickstart/universal.md
app/docs/1.3.x/quickstart/universal.md
app/docs/1.4.x/quickstart/universal.md
app/docs/1.5.x/quickstart/universal.md
app/docs/1.6.x/quickstart/universal.md
app/docs/1.7.x/quickstart/universal.md
app/docs/1.8.x/quickstart/universal.md
app/docs/2.0.x/quickstart/universal.md

The old redis ones are 404ing, probably they broke their docs.

chore(links): fix 404'd redis links

---

app/_posts/2023-02-01-kuma-2-1-0.md
app/_posts/2023-06-23-kuma-2-3-0.md
app/_src/policies/meshhttproute.md
app/_src/policies/meshtcproute.md

The examples in the blogpost / httproute / tcproute look like they should work with the marketplace demo but they **actually don't** (`kuma.io/service` is the same, but version tags and prefix is wrong).
This combined with the "catch all" route causes an invalid MeshHTTPRoute to "sort of work" without any warning and can cause confusion down the line.
E.g. if we take the old MeshHTTPRoute with a 90/10 split:
```yaml
default:
backendRefs:
- kind: MeshServiceSubset
name: backend_kuma-demo_svc_3001
tags:
version: "1.0"
weight: 90
- kind: MeshServiceSubset
name: backend_kuma-demo_svc_3001
tags:
version: "2.0"
weight: 10
```
this produces the following envoy configuration:
```yaml
- match:
path: "/api"
route:
weighted_clusters:
clusters:
- name: backend_kuma-demo_svc_3001-de1397ec09e96dfb …
```

docs(routing): make the examples work for marketplace demos

---

app/_src/policies/meshhttproute.md

Fix a few invalid examples using invalid tag syntax (`v1/experimental` -> "tag value must consist of alphanumeric characters, dots, dashes and underscores").

chore: fix invalid tag in MeshHTTPRoute examples

---

app/_src/guides/gateway-builtin.md

Using `kuma.io/service` is deprecated

chore(guides): drop deprecated kuma.io/service in gateway

---

app/_src/policies/meshaccesslog.md

closes https://github.com/kumahq/kuma-website/issues/1538
rendered: https://deploy-preview-1739--kuma.netlify.app/docs/2.6.x/policies/meshaccesslog/#opentelemetry
Not tested manually (let me know if I should do this), based on:
- https://github.com/open-telemetry/opentelemetry-proto/issues/167
- https://github.com/open-telemetry/opentelemetry-collector/blob/7a8954f6b83851c532fc4190ee5b17c8584a2671/pdata/internal/json/attribute.go#L33-L75
- https://github.com/open-telemetry/opentelemetry-proto/issues/167
- https://github.com/open-telemetry/opentelemetry-collector/issues/1363
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md …

feat(meshaccesslog): add more info to body types

---

app/_src/index.md

Looks like there is some strange markdown behaviour with `if_version`.
This PR just amends one problem, but doesn't solve whatever the issue is. Happy to close if someone has a better solution.

fix(docs): ensure getting started links have a return between them

---

.github/workflows/ci.yml
app/installer.sh

`gh` requires a valid token - in this PR I exchange it for cloudsmith which does not and now people who don't have a valid token can try out the preview version

feat(installer): use cloudsmith instead of gh to fetch preview version

---

app/installer.sh

There was an unsued variable from the graphql version and `kong mesh` needs to be `kong-mesh`
```
$ PRODUCT_NAME='Kong Mesh' VERSION=preview app/installer.sh --print-version
INFO    Welcome to the Kong Mesh automated download!
INFO    Fetching latest preview commit..
INFO    Found preview commit: https://github.com/kumahq/kuma/commit/7bf655a7a
0.0.0-preview.v7bf655a7a
```

fix(installer): fix installer for kong mesh

---

app/_src/using-mesh/managing-ingress-traffic/builtin.md

docs(gateway): fix image in example resource

---

app/_includes/snippets/warning_meshgatewayinstance_service_tag.md
app/_src/using-mesh/managing-ingress-traffic/builtin-k8s.md
app/_src/using-mesh/managing-ingress-traffic/builtin-listeners.md
app/_src/using-mesh/managing-ingress-traffic/builtin.md

Update builtin gateway docs after deprecation of specifying `kuma.io/service` tag in `MeshGatewayInstance`
Closes https://github.com/kumahq/kuma-website/issues/1745
Rendered modified pages:
- https://deploy-preview-1748--kuma.netlify.app/docs/2.7.x/using-mesh/managing-ingress-traffic/builtin/
- https://deploy-preview-1748--kuma.netlify.app/docs/2.7.x/using-mesh/managing-ingress-traffic/builtin-k8s/
- https://deploy-preview-1748--kuma.netlify.app/docs/2.7.x/using-mesh/managing-ingress-traffic/builtin-listeners/

docs(gateway/builtin): update gateway docs after service tag deprecation in MeshGatewayInstance

---

Makefile
Procfile
netlify.toml
package.json
yarn.lock

Install the netlify-cli package in the project instead of globally.
Note: the packages in package.json are _very_ outdated. It doesn’t look like we’re using Dependabot here.

chore: install netlify-cli in project instead of globally

---

app/_src/policies/meshtimeout.md
app/_src/quickstart/kubernetes-demo.md

* typo in `backendRefs`
* replace `MeshService` with `MeshSubset` as `MeshService` is deprecated in `from`

fix(quickstart): replace `from.MeshService` with `from.MeshSubset`

---

app/_src/production/dp-config/transparent-proxying.md

Fix kuma-dp's transparent-proxying docs
- Mentioning not supported nftables is wrong from 2.5.6
- We are not by default excluding port 22 from redirection anymore
Link to updated page: https://deploy-preview-1787--kuma.netlify.app/docs/2.7.x/production/dp-config/transparent-proxying/

docs(kuma-dp): fix kuma-dp's transparent-proxy docs

---

app/_src/production/upgrades-tuning/upgrade-notes.md

Fix a `{% tip %}` in doc.
There was a warning logged while building the site.
Liquid tags should be `{% tag %}`, `{{ ... }}` is used for interpolating values.

Fix {% tip %} in doc

---

app/_src/networking/dns.md
app/docs/1.2.x/networking/dns.md
app/docs/1.3.x/networking/dns.md
app/docs/1.4.x/networking/dns.md
app/docs/1.5.x/networking/dns.md
app/docs/1.6.x/networking/dns.md
app/docs/1.7.x/networking/dns.md
app/docs/1.8.x/networking/dns.md
app/docs/2.0.x/networking/dns.md

DNS `AAAA` records match a domain name to an IPv6 address, not `AAAAA`
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)? - yes

docs: fix IPv6 DNS record typo

---

app/_src/production/dp-config/cni.md

Once install kuma-cni with cilium/calico CNI on GKE platform, we should follow the GKE section rather than the original cilium/calico instruction.
close #1753 
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?- yes

chore(docs): clarify CNI installation section for cilium/calico on GKE

---

app/_src/guides/otel-metrics.md

Refer to openTelemetry helm installation [UPGRADING](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/UPGRADING.md#0880-to-0890),  the openTelemetry helm requires the parameter `image.repository` must be set.
Notice: There are 2 options for this parameter, and `OpenTelemetry Collector Kubernetes Distro` will be the default image used for the chart(And we also need to update our [OpenTelemetry collector configuration](https://kuma.io/docs/2.7.x/guides/otel-metrics/#install-opentelemetry-collector)). Currently, we use `Contrib distribution` for transitions.
OpenTelemetry Collector Kubernetes Distro
```text
image:
repository: "otel/opentelemetry-collector-k8s"
```
Contrib distribution
```text
image:
repository: …
```

chore(docs): improve openTelemetry installation command

---

app/_src/reference/kubernetes-annotations.md

xref https://github.com/kumahq/kuma/pull/10580
We need to recommend labels instead of annotations. It already works on Pod, but on namespace it will from 2.8

fix(reference): labels and annotations to setup mesh

---

app/_src/policies/meshfaultinjection.md

xref: https://github.com/kumahq/kuma/pull/10371

docs(meshfaultinjection): use proper metric prefix

---

.vale.ini

From [latest release](https://github.com/errata-ai/vale/releases/tag/v3.6.1):
> https://github.com/errata-ai/vale/commit/f7cbb579a821023c0fd8497b3866205f11e57e7a refactor: error on misplaced core-level settings

ci(vale): fix config

---

app/_src/production/dp-config/cni.md

After https://github.com/kumahq/kuma/pull/10906 there won't be `redirectPortInboundV6` and this form basically have never worked

fix(cni): update install command for AWS EKS with CNI

---

app/_src/policies/traffic-permissions.md

The Mesh Traffic Permissions doc displays the name "Kuma": https://docs.konghq.com/mesh/latest/policies/traffic-permissions/
This PR changes the hardcoded name to a variable so that the right product name displays. 
Also fixing a typo, removing an extra `[` character next to a link.

docs(MeshTrafficPermission): use variable for kuma product name

---

app/_src/explore/observability.md

Service can be used by a lot of things and cause label collision kuma_service is a better alternative.
Dashboards currently don't use this label which makes it better.
part of kong/kong-mesh#4576

fix(observability): delete service label in prometheus scrape

---

app/_src/production/dp-config/cni.md

docs(cni): note about `cni.exclusive` with Cilium

---

app/_src/policies/meshaccesslog.md

fix(meshaccesslog): use /dev/stdout in examples

---

app/_posts/2024-06-25-kuma-2-8-0.md

was not rendering `.DisplayName`
rendered: https://deploy-preview-1894--kuma.netlify.app/blog/2024/kuma-2-8-0/

fix(blog): fix blogpost template

---

app/_src/guides/migration-to-the-new-policies.md

otherwise we can't link to steps, it always goes to top of the page https://kuma.io/docs/2.8.x/guides/migration-to-the-new-policies/#migration-to-the-new-policies :(

fix(guide): fix not being able to link to migration steps heading because of duplication

---

app/_src/networking/meshservice.md

Not relevant before this point

chore: only show MeshService migration from 2.9

---

app/_redirects

the install button was leading to the old install site

fix(install): change install link to the new webpage

---

package.json
yarn.lock

chore(deps): manually bump exress to 4.21.0

---

app/_src/explore/gateway-api.md
app/_src/using-mesh/managing-ingress-traffic/gateway-api.md

No need for these resources when trying out Gateway API. Closes https://github.com/kumahq/kuma-website/issues/1924

docs(gateway-api): use `--without-gateway` with `install demo`

---

app/_src/networking/meshexternalservice.md
app/_src/policies/meshpassthrough.md

Fix: https://github.com/kumahq/kuma-website/issues/1830
`proxyTypes` doesn't need clarification because it's part of a `targetRef` and not specific to any particular policy. The documentation in that context already explains it.

docs(policy): fixed docs of meshpassthrough and meshexternalservice

---

app/_src/policies/meshtls.md

I feel that users are likely to change the mode more frequently than the cipher, so the mode should be presented first in the tab for easier understanding.

docs(meshtls): change tab order

---

app/_src/networking/meshservice.md
jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/policyyaml.rb

`kuma-system` doesn't make sense
https://deploy-preview-1952--kuma.netlify.app/docs/dev/networking/meshservice/#meshservice

fix(MeshService): namespace on example

---

app/_assets/javascripts/tabs.js
app/_assets/styles/custom/components/_vuepress-tabs.scss

Pages where "jumping" when clicking on tabs because the difference in height (and that we toggle all the tabs with the same slug).
As proposed in slack scroll tabs to top on click 

Scroll tabs to top on click

---

.github/workflows/ci.yml
app/_data/docs_nav_kuma_2.9.x.yml

Adds navigation for `release-2.9.x` and fixes `404` on `/docs/2.9.x`.
Also fixes ci error in `Docs lint` due to [error: externally-managed-environment on ubuntu ubuntu-24.04](https://github.com/errata-ai/vale-action/issues/128) when installing `docutils`, by pin ubuntu to `22.04`.

feat(app/nav): add 2.9.x

---

app/_data/docs_nav_kuma_2.9.x.yml

I think mistakenly the 2.9 navbar was copied from 2.8 and not dev

chore(navbar): fix 2.9 navbar

---

app/_src/quickstart/kubernetes-demo.md

From 2.9 this is deprecated so let's avoid having a quickstart guide with deprecated examples...

fix(quickstart): don't use MeshService in spec.targetRef

---

.github/workflows/ci.yml
.vale.ini

This will only show errors as annotations on the diff.
We are currently not showing anything from Vale. This will show errors. For example, rejected word errors

ci(vale): fix reporter, only annotate errors

---

.github/styles/config/vocabularies/Base/accept.txt
app/_src/guides/federate.md
app/_src/guides/gateway-builtin.md
app/_src/guides/gateway-delegated.md
app/_src/quickstart/kubernetes-demo.md

- Updated installation instructions to use Minikube instead of Kind.
- Modified references throughout relevant pages to reflect Minikube.
- Ensured steps are clear for users to set up Minikube.
Closes #1649
Signed-off-by: dascole joe.dascole@konghq.com

docs(install): replace Kind with Minikube for simple test installations

---

CONTRIBUTING.md

Restructured `CONTRIBUTING.md` section `Running the site locally` into sections `Setup`, `Development`, `Production build` and added more information.
I faced some issues when running `make install` on a fairly fresh system (M3):
- Missed to install `yarn`
- Error when installing gem `posix-spawn`. This is possibly not limited to `posix-spawn` though. Added the instructions to resolve this.

chore(contributing): update docs

---

app/_src/explore/gateway.md
app/_src/guides/gateway-builtin.md
app/_src/policies/meshgateway.md
app/_src/using-mesh/managing-ingress-traffic/builtin-listeners.md
app/_src/using-mesh/managing-ingress-traffic/builtin-routes.md

Fixes: #1810
We will improve validation in next release to so that won't be able to shoot themselves in the foot: https://github.com/kumahq/kuma/issues/11806

fix(gateway): don't use MeshGateway tags that cannot be referenced from Mesh*Route

---

.vale.ini

This way we'll get an error when the capitalization in a heading is wonky

ci(vale): enforce heading capitalization

---

app/_src/policies/meshaccesslog.md

The table was broken because there is gte:2.9.x and gte:2.4.x so it renders two tables (as one)
Maybe we can do some double nesting but I think better option is just to add small annotation on all versions
Fix https://github.com/kumahq/kuma-website/issues/1917

fix(policies): mesh access log target ref table

---

app/_src/quickstart/kubernetes-demo.md

We've updated Universal quickstart guide. We can now align Kuberentes guide with it. This change will also simplify kuberenetes quickstart

fix(kubernetes): align kubernetes quickstart mtls example with universal quickstart

---

jekyll-dev.yml
jekyll.yml

Adjust `jekyll-dev.yml` to be equivalent to `jekyll.yml` with all fields using the same characters in string literals, the same positions.
The most important change is setting `kramdown.syntax_highlighter_opts.span.disable` to `true`, which makes generated code wrapped in backticks to look the same in dev as in prod.
No other changes have any impact on generated builds.
As a result on below screen you can see the only differences between prod and dev config files:

chore(conf): make jekyll configuration files consistent

---

app/_src/guides/migration-to-the-new-policies.md

Use `kubectl label`, add commands for each instruction
Part of https://github.com/kumahq/kuma-website/issues/1961
[Rendered](https://deploy-preview-2013--kuma.netlify.app/docs/2.9.x/guides/migration-to-the-new-policies/#trafficpermission---meshtrafficpermission)

docs(migration): improve labeling, add commands to delete old policies

---

app/_src/introduction/kuma-requirements.md

Rewrite Kubernetes and envoy requirements page to make it easier to understand and dependent on actual Kuma version. This should now show actual version of Envoy used in release and versions of k8s against which Kuma was validated

fix(requirements): rewrite kubernetes and envoy requirements page

---

app/_data/docs_nav_kuma_2.9.x.yml
app/_data/docs_nav_kuma_dev.yml
app/_src/policies/introduction.md

Navbar was missing and the page is super long. Navbar in this case improves navigation.
Also two small nits:
* policy_yaml does not work with old policies (MeshGateway is considered old in this case, because it does not have spec)
* Add more clarification to Sidecar / Gateway selector

docs(policies): add navbar to introduction

---

app/_layouts/features.html

It does not make sense to point people with request feature to add them on docs instead on main Kuma repo

fix(features): change link for requesting features to kuma repo as we store feature requests there

---

app/_src/guides/migration-to-the-new-policies.md

Part of https://github.com/kumahq/kuma-website/issues/1961
[Rendered](https://deploy-preview-2016--kuma.netlify.app/docs/2.9.x/guides/migration-to-the-new-policies/#meshgatewayroute---meshhttproutemeshtcproute)

docs(migration): add gateway setup

---

app/_src/policies/meshcircuitbreaker.md

feat(mcb): fix support matrix for MeshCircuitBreaker policy

---

app/_src/policies/meshfaultinjection.md

feat(mfi): fix support matrix for MeshFaultInjection policy

---

app/_src/policies/meshhttproute.md

feat(mhttpr): fix support matrix for MeshHttpRoute policy

---

app/_src/policies/meshhealthcheck.md

feat(mhc): fix support matrix for MeshHealthCheck policy

---

app/_src/policies/meshtrafficpermission.md

feat(mtp): fix support matrix for MeshTrafficPermission policy

---

app/_src/policies/meshmetric.md

feat(mm): fix support matrix for MeshMetric policy

---

app/_src/policies/meshretry.md

feat(mr): fix support matrix for MeshRetry policy

---

app/_src/policies/meshtcproute.md

feat(mtcpr): fix support matrix for MeshTCPRoute policy

---

app/_src/policies/meshtrace.md

feat(mtr): fix support matrix for MeshTrace policy

---

app/_src/policies/meshproxypatch.md

feat(mpp): fix support matrix for MeshProxyPatch policy

---

app/_src/policies/meshtimeout.md

feat(mtcpr): fix support matrix for MeshTimeout policy

---

app/_src/policies/meshratelimit.md

feat(mrl): fix support matrix for MeshRateLimit policy

---

app/_src/policies/meshloadbalancingstrategy.md

feat(mlbs): fix support matrix for MeshLoadBalancingStrategy policy

---

app/_src/policies/meshaccesslog.md

feat(mal): fix support matrix for MeshAccessLog policy

---

app/_src/guides/consumer-producer-policies.md

if a producer policy has a timeout of 1s and the request takes 2 seconds it should timeout

docs(guide): fix expected output on testing producer policies

---

app/_assets/javascripts/sidebar.js

Until now when clicked on nested link in sidebar, it was broken when you wanted to nest more than 1 level. This changes fixes the issue

fix(script): fix sidebar.js script to properly support nested groups

---

app/_src/policies/meshloadbalancingstrategy.md
app/_src/policies/meshmetric.md

For some reason we were using not default mesh in examples which was confusing for users

fix(policies): fix policy examples to use default mesh

---

app/_data/docs_nav_kuma_2.9.x.yml
app/_data/docs_nav_kuma_dev.yml
app/_src/guides/gateway-api.md
app/_src/using-mesh/managing-ingress-traffic/gateway-api.md

Old guide is not working. I have fixed it and I would like to move it to guides section

fix(guide): fix and move guide for Kubernetes Gateway API

---

app/_assets/styles/custom/components/_sidebar.scss
app/_assets/styles/custom/components/_version-nav.scss
app/_assets/styles/vuepress-core/algolia-search.scss
app/_assets/styles/vuepress-core/sidebar.scss
app/_includes/sidebar.html

Fixed an issue where the sticky positioning of the version selector and search bar caused the search results container to be cut off
---
---
---
---

fix(styles): ensure search results visibility

---

app/_src/policies/meshmetric.md

Remove the `experimental` designation for OTEL in MeshMetric.

remove mesh metric otel from experimental

---

app/_src/production/dp-config/dpp-on-kubernetes.md

Fixed misleading kuma-init example in container patches. Previous example was incorrect and wouldn't work.
Additionally fixed few small unrelated mistakes.
---

fix(docs): correct kuma-init container patch example in dpp on k8s

---

Makefile
netlify.toml

1. Removed redirection for `/vite-dev/*` in `netlify.toml` because it was unnecessary and it was causing that during `make run` vite-related scripts were loaded twice, so you could see in the console it was connecting to vite's websocket server twice
2. Updated `clean` make target, so it currently cleans up all build-related files and directories
3. Small improvement if formatting of `netlify.toml` file
---

chore(dev): fix small issuse with netlify conf and cleanup make target

---

Makefile

In order to use the `netlify-cli` without installing it globally we can use `npx`.
```bash
$ make run
netlify dev
bash: netlify: command not found
make: *** [run] Error 127
```

chore(mk/run): use npx to execute netlify-cli

---

app/_src/production/cp-deployment/zone-ingress.md
app/_src/production/cp-deployment/zoneegress.md

Should be `Server Name Indication` instead of `Service Name Indication`.

fix(prod/cp-deployment): typo SNI

---

app/_src/policies/meshhttproute.md

Just a missing `is`. Aligns with `MeshTCPRoute`.

fix(policies/meshhttproute): typo

---

app/_src/quickstart/kubernetes-demo.md
app/_src/quickstart/universal-demo.md

After finishing the quickstart, I thought it would be nice to add links to the docs for single and multi-zone deployments. These also show how to use `kumactl` for cp deployments.

feat(quickstart): add links to single and multi-zone cp deployment

---

app/_src/policies/mutual-tls.md
app/docs/1.3.x/policies/mutual-tls.md
app/docs/1.4.x/policies/mutual-tls.md
app/docs/1.5.x/policies/mutual-tls.md
app/docs/1.6.x/policies/mutual-tls.md
app/docs/1.7.x/policies/mutual-tls.md
app/docs/1.8.x/policies/mutual-tls.md
app/docs/2.0.x/policies/mutual-tls.md

Because the actual field is `conf` - https://github.com/kumahq/kuma/blob/f8179d7a8d0348a67ac7e7983e6d65c1fee339ed/api/mesh/v1alpha1/mesh.pb.go#L281

fix(mesh): rename config to conf

---

app/_data/docs_nav_kuma_2.10.x.yml
app/_data/docs_nav_kuma_2.9.x.yml
app/_data/navigation.yml
app/_src/guides/federate.md
app/_src/index.md
app/_src/introduction/how-kuma-works.md
app/_src/introduction/install.md
app/_src/production/dp-config/cni.md
app/_src/production/index.md
app/_src/production/use-mesh.md
app/index.md

Kuma in page names is problematic with the entreprise version of docs.

fix(install): move install page to not have Kuma

---

app/_src/production/install-kumactl.md

A supplement to https://github.com/kumahq/kuma-website/pull/2107
Preview link: https://deploy-preview-2109--kuma.netlify.app/docs/2.8.x/production/install-kumactl/#install-kumactl
* Yes
* Yes

docs(production): fix installer link in doc 'install-kumactl'

---

app/_includes/version_selector.html
app/_layouts/install.html
app/install/latest.md

Since the move to the latest version of the single page generator we are showing banners when we shouldn't and the dropdown was not picking the right version
Fix #2090

fix(install): install is showing odd versions

---

.github/workflows/ci.yml

I got some checklinks failure but it did works from my PC:
```text
https://deploy-preview-2114--kuma.netlify.app/docs/2.9.x/production/dp-config/cni/
403	https://docs.cilium.io/en/v1.14/operations/upgrade/#id2
https://deploy-preview-2114--kuma.netlify.app/docs/2.9.x/production/cp-deployment/kubernetes/
403	https://argo-cd.readthedocs.io/en/stable/
https://deploy-preview-2114--kuma.netlify.app/docs/2.7.x/production/dp-config/cni/
403	https://docs.cilium.io/en/v1.14/operations/upgrade/#id2
https://deploy-preview-2114--kuma.netlify.app/docs/2.7.x/production/cp-deployment/kubernetes/
403	https://argo-cd.readthedocs.io/en/stable/
https://deploy-preview-2114--kuma.netlify.app/docs/2.8.x/production/dp-config/cni/
403	https://docs.cilium.io/en/v1.14/operations/upgrade/#id2 …
```

ci(checklinks): exclude external website from checklinks

---

app/_data/docs_nav_kuma_2.9.x.yml
app/_src/production/deployment/high-availability.md

Some questions have come up about this. Let's add a note about this, something that shows up when you search "high availability".
[Rendered](https://deploy-preview-2124--kuma.netlify.app/docs/2.9.x/production/deployment/high-availability/)

docs(kuma-cp): add short explanation of high availability

---

.github/styles/config/vocabularies/Base/accept.txt
app/_src/networking/meshexternalservice.md

I've simplified some parts of MES docs, and added an example on how to disable traffic to MES

feat(mes): add example of disabling traffic to MeshExternalService on Mesh

---

app/_includes/sidebar.html
app/_includes/version_selector.html

We were not using the label so the link was using the version number instead of `dev`

fix: invalid link to dev in drowndown sidebar

---

app/_src/policies/meshtrafficpermission.md

When I went through the MeshTrafficPermission source codes and found we need to enable the mTLS then the MTP policy works.
https://github.com/kumahq/kuma/blob/2.9.2/pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go#L51-L56

docs(MeshTrafficPermission): Add a note to enable mTLS to make mtp works

---

.github/workflows/ci.yml

https://jwt.io/ is clearly blocking GH requests - it works normally from a browser, we need to exclude it to make the link checker pass
https://github.com/kumahq/kuma-website/actions/runs/13179405471/job/36786218554?pr=2165#step:6:27

fix(lint): exclude jwt.io

---

app/_src/policies/timeout.md
app/_src/policies/traffic-permissions.md
app/_src/policies/traffic-route.md

Since {{site.mesh_product_name}} version 2.6.x, default legacy policies are no longer created when a new mesh is created. I've added a note about this change.

docs(policies): added note that old policies are not created by default

---

app/_src/networking/meshexternalservice.md

Since 2.9.x we require Egress and mTLS to use MeshExternalService

fix(meshexternalservice): added information about egress and mtls 

---

app/_src/production/secure-deployment/dp-auth.md

A followup of changes in Kuma. Recent Kuma PRs introduced a change to the DP authentication that impacts the behaviour of Universal zones.
Kuma PRs:
* https://github.com/kumahq/kuma/pull/12788
* https://github.com/kumahq/kuma/pull/12828
* Yes
* Yes

docs(dp-auth): add note for dataplane token revocation

---

app/_src/production/secure-deployment/dp-auth.md

We were referencing old property which doesn't exist anymore

docs(dp-auth): fix env variable

---

app/_src/policies/meshcircuitbreaker.md
app/_src/policies/meshhealthcheck.md

In Kuma `2.10.*` , the `healthyPanicThreshold` field will be deprecated in `MeshHealthCheck` policy, and the setting has been moved to `MeshCircuitBreaker` policy. Please use `MeshCircuitBreaker` policy instead. 

feat(policy): move healthyPanicThreshold field from MeshHealthCheck to MeshCircuitBreaker

---

app/_src/policies/meshaccesslog.md
app/_src/policies/meshcircuitbreaker.md
app/_src/policies/meshfaultinjection.md
app/_src/policies/meshhealthcheck.md
app/_src/policies/meshhttproute.md
app/_src/policies/meshloadbalancingstrategy.md
app/_src/policies/meshmetric.md
app/_src/policies/meshpassthrough.md
app/_src/policies/meshproxypatch.md
app/_src/policies/meshratelimit.md
app/_src/policies/meshretry.md
app/_src/policies/meshtcproute.md
app/_src/policies/meshtimeout.md
app/_src/policies/meshtls.md
app/_src/policies/meshtrace.md
app/_src/policies/meshtrafficpermission.md

In 2.10 we are adding new top level kind Dataplane. This PR updates targetRef support matrix with new kind

feat(dataplane): add new kind dataplane in policies top level targetRef

---

app/_src/policies/meshaccesslog.md
app/_src/policies/meshcircuitbreaker.md
app/_src/policies/meshfaultinjection.md
app/_src/policies/meshhealthcheck.md
app/_src/policies/meshhttproute.md
app/_src/policies/meshloadbalancingstrategy.md
app/_src/policies/meshmetric.md
app/_src/policies/meshpassthrough.md
app/_src/policies/meshratelimit.md
app/_src/policies/meshretry.md
app/_src/policies/meshtcproute.md
app/_src/policies/meshtimeout.md
app/_src/policies/meshtls.md
app/_src/policies/meshtrace.md
app/_src/policies/meshtrafficpermission.md

We've added new kind Dataplane we should use it in policies examples in favour of deprecated MeshSubset

feat(dataplane): use dataplane kind in policy examples

---

app/_assets/styles/vuepress-core/index.scss

- Increased h4 and h5 sizes to improve readability
- Fixed cases where headers appeared smaller than section content
- Ensured better visual hierarchy in documentation
---
<table>
<thead><tr><th>Before</th><th>After</th></tr></thead>
<tbody>
<tr>
<td><img width="253" alt="Screenshot 2025-03-06 at 12 43 21" src="https://github.com/user-attachments/assets/fa382cc0-c6a7-4b27-b263-6cdf9cafd6a3" /></td>
<td>
</tr>
</tbody>
</table>
---

style: adjust h4 and h5 sizes for better readability

---

app/_data/docs_nav_kuma_2.10.x.yml
app/_data/docs_nav_kuma_2.2.x.yml
app/_data/docs_nav_kuma_2.3.x.yml
app/_data/docs_nav_kuma_2.4.x.yml
app/_data/docs_nav_kuma_2.5.x.yml
app/_data/docs_nav_kuma_2.6.x.yml
app/_data/docs_nav_kuma_2.7.x.yml
app/_data/docs_nav_kuma_2.8.x.yml
app/_data/docs_nav_kuma_2.9.x.yml
app/_src/production/secure-deployment/certificates.md

Fixed typo in word `across` (`accross` -> `across`)
---

fix: typo in word "across"

---

app/_src/explore/observability.md

It seems datadog changed the docs structure and https://docs.datadoghq.com/agent/basic_agent_usage is no longer a valid link
---

chore: fix broken datadog agent links

---

.github/styles/config/vocabularies/Base/accept.txt
CONTRIBUTING.md
Makefile

Added troubleshooting steps for macOS 15 installation errors during `make install`, including Xcode reinstallation and Ruby recompilation. Also improved the Mutagen sync guide by adding commands to monitor and terminate synchronization.
---

feat(docs): add macOS 15 install fix and improve Mutagen sync guide

---

app/_src/quickstart/universal-docker-demo.md

- Added logs checks to confirm containers are running and data plane proxies start successfully
- Included instructions for verifying transparent proxy installation via the logs
- Fix: Used `${KUMA_DEMO_TMP}` for mounted volumes instead of plain paths
- Improved descriptions for setting the zone name and confirming success message
- Fix link for `Exclusive` mode for MeshServices
Fixes https://github.com/kumahq/kuma-website/issues/2256
---

docs(quickstart/universal): refine instructions and add verification steps

---

app/_data/docs_nav_kuma_2.10.x.yml
app/_data/docs_nav_kuma_2.11.x.yml
jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/jsonschema.rb

guide added in 2.10.x was missing in preview navbar

fix(nav): add missing guide to preview navbar

---

app/_src/policies/meshloadbalancingstrategy.md

When you enable the MeshService, you need to specify MeshMultiZoneService in MeshLoadBalancingStrategy policy for traffic across zones
close #2249 

fix(MeshLoadBalancingStrategy): specify MeshMultiZoneService for traffic across zones when MeshService is enabled

---

jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/policyyaml.rb
spec/fixtures/mhr-port.golden.html
spec/fixtures/mhr-port.yaml
spec/fixtures/mhr-port_dev.golden.html
spec/fixtures/mhr-port_edition.golden.html

Otherwise it can create keys like:
```
│ Error: Reference to undeclared resource
│
│   on main.tf line 137, in resource "konnect_mesh_traffic_permission" "example_with_tags":
│  137:             kuma.io/zone = "us-east"
│
│ A managed resource "kuma" "io" has not been declared in the root module.
```

feat(tf): quote slash character in keys

---

app/_src/policies/meshtrace.md

closes https://github.com/kumahq/kuma-website/issues/2199
after https://github.com/kumahq/kuma/pull/12895 there's been some changes to properties and if there are people using older versions and use the corrected examples this will minimise the work needed when ugprading
Checked:
- requestRedirect.statusCode - no in examples in docs
- apiVersion - changed in the PR
- MeshMetric's path - all examples have `path`
- passthroughMode - all examples have `passthroughMode`

chore(examples): adjust examples to upgrade.md

---

app/_src/policies/introduction.md
app/_src/policies/targetref.md

Removing a property using null does not work because of go serialization. I fixed the docs to reflect that.

fix(merging): removing a property using `null` does not work

---

jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/policyyaml.rb
spec/fixtures/mhr-port_edition.golden.html

as per  https://github.com/Kong/docs.konghq.com/pull/8553#issuecomment-2738074944
this is how it looks like:

feat(tf): automatically add my_meshcontrolplane.id and mesh.name

---

app/_src/policies/meshaccesslog.md
app/_src/policies/meshcircuitbreaker.md
app/_src/policies/meshfaultinjection.md
app/_src/policies/meshhealthcheck.md
app/_src/policies/meshhttproute.md
app/_src/policies/meshloadbalancingstrategy.md
app/_src/policies/meshmetric.md
app/_src/policies/meshpassthrough.md
app/_src/policies/meshproxypatch.md
app/_src/policies/meshratelimit.md
app/_src/policies/meshretry.md
app/_src/policies/meshtcproute.md
app/_src/policies/meshtimeout.md
app/_src/policies/meshtls.md
app/_src/policies/meshtrace.md
app/_src/policies/meshtrafficpermission.md

Fix: https://github.com/kumahq/kuma-website/issues/2277

fix(targetref): add back MeshSubset to targetRef support matrix and mark it as deprecated

---

app/_src/introduction/kuma-requirements.md

Pre: 
because `"2.10" | truncate 3` evaluates to "2.1"
After:

fix(requirements): use page.version_data.branch otherwise truncating fails on 2.10

---

package.json
yarn.lock

Dependabot is failing because:
```
Dependabot cannot update path-to-regexp to a non-vulnerable version
The latest possible version that can be installed is 0.1.10 because of the following conflicting dependency:
express@4.21.0 requires path-to-regexp@0.1.10
The earliest fixed version is 0.1.12.
[Troubleshoot Dependabot errors](https://docs.github.com/github/managing-security-vulnerabilities/troubleshooting-dependabot-errors)
```
I don't think we're using `express` anywhere - let's see if this builds.
Fixes: …

chore(deps): get rid of express

---

app/_src/guides/otel-metrics.md

closes https://github.com/kumahq/kuma-website/issues/2151
Adding a note on how to login grafana using its default credential.
* yes
* yes

docs(otel): add note for grafana login page

---

app/_src/policies/meshtimeout.md

This changes MeshTimeout policy examples to use demo-app. Thanks to this, you can just copy and paste them when running demo

feat(meshtimeout): update MeshTimeout examples to use demo app

---

jekyll-kuma-plugins/lib/jekyll/kuma-plugins/liquid/tags/rbacresources.rb

Add support for locating the input YAML file using a default filename (`rbac.yaml`) and a set of base paths from `mesh_raw_generated_paths` in `jekyll.yml`. The plugin builds the full path using the current `page.release`. Falls back to the given path if not found. Raises an error if the file cannot be located.
---

feat(jekyll/plugin/rbacresources): support configurable and default search paths for input file

---

app/_src/explore/gateway.md
app/_src/using-mesh/managing-ingress-traffic/delegated.md

Seems like anchors have new structure.
We used to link to https://docs.konghq.com/kubernetes-ingress-controller/3.1.x/reference/annotations/#ingresskubernetesioservice-upstream and now the correct link is https://developer.konghq.com/kubernetes-ingress-controller/reference/annotations/#ingress-kubernetes-io-service-upstream (notice new `-`).

chore(links): change link due to developer.konghq.com migration

---

app/_src/production/dp-config/dpp.md

Fixed a broken link in the Outbounds section of the [DP proxy page](https://developer.konghq.com/mesh/data-plane-proxy/#outbounds). It was missing link text, so I've added that.

Fix: Broken transparent proxying link in Outbound

---

app/_src/production/dp-config/transparent-proxying.md

Example was missing `annotations` field

fix: reachable backend Kubernetes examples

---

app/_src/production/dp-config/dpp-on-kubernetes.md

It's not mentioned in the docs that policies don't work when you use direct-access

docs(direct-access): add info about policies not working when direct-access is used

---

.github/workflows/ci.yml

This fails constantly, we are excluding all external links for now. We will move this functionality either to manual step on release or we will look for alternative

fix(ci): exclude all external links from link checker
